### ISSUE TITLE
Update from 0.1.1096 to 0.2.15: Multiple Compilation Errors

### ISSUE THREAD

**Issue by HarryCordewener** [thomhurst/TUnit#1006]
As usual, using my repository for checking out new versions of TUnit: 
https://github.com/SharpMUSH/SharpMUSH

I'm going to include the errors as a Text File this time, because it's a lot of them. But it's of course largely repeats of various things.

[TUnit Upgrade.txt](https://github.com/user-attachments/files/17528923/TUnit.Upgrade.txt)

**Comment by HarryCordewener** [comment]
PR of changes related to this:
https://github.com/SharpMUSH/SharpMUSH/pull/64 

Log of errors on Github:
https://github.com/SharpMUSH/SharpMUSH/actions/runs/11528756570

**Comment by thomhurst** [comment]
@HarryCordewener Can you remove the package `<PackageReference Include="TUnit.Engine.SourceGenerator" Version="0.1.984" />` ?

**Comment by HarryCordewener** [comment]
That indeed fixed the build. Though now Visual Studio never has the tests return to it, and Rider takes quite a while to run them.

Same with dotnet test:
https://github.com/SharpMUSH/SharpMUSH/actions/runs/11528611519/job/32095969064 - Old: 1 minute 27s
https://github.com/SharpMUSH/SharpMUSH/actions/runs/11533078111/job/32105579649 - New: 3 minute 24s

![image](https://github.com/user-attachments/assets/56a0f667-23f7-49cf-a2e9-c16f042e2dd8)
After forcing a stop:
![image](https://github.com/user-attachments/assets/b560c7be-2c63-49a8-af74-34cbff76c8a2)

**Comment by thomhurst** [comment]
I think I might know why. I tried to make the source generator generate a file per test class, but this involves it having to aggregate all the files at once in order for me to filter and group them.

I've reverted this, can you let me know if it improves performance?

Version 0.2.30

**Comment by HarryCordewener** [comment]
That did fix performance for Rider etc, though Visual Studio Preview is still failing to report on findings.
Since `dotnet test` and `rider` can run just fine, this to me just reads as a Visual Studio Preview bug. I dunno.

**Comment by thomhurst** [comment]
> That did fix performance for Rider etc, though Visual Studio Preview is still failing to report on findings. Since `dotnet test` and `rider` can run just fine, this to me just reads as a Visual Studio Preview bug. I dunno.

That's good news. I don't think it's a TUnit problem. I've recently added tests to assert I'm sending discovery messages.

Happy to be proven wrong but it also seems to work fine on my machine. (Famous words!)

If you can create a repo reproduction though then please do as that'd help.

**Comment by HarryCordewener** [comment]
It's reproducible on my repo, but would need Docker Desktop installed to run it.

But for now, rider will work. Especially now that it's free for non-commercial use. Just crashes more often than VS.
Edit: VSCode has the same issue.

**Comment by thomhurst** [comment]
Very weird that it works in rider but not vs. but if you can produce a mini repro send it over and I can try and investigate!

Vs seems to work fine for me

**Comment by HarryCordewener** [comment]
Trying to generate a mini-repo, but can't even get it to compile at the moment:
https://github.com/HarryCordewener/sample-repo-for-tunit

![image](https://github.com/user-attachments/assets/4e841633-4767-45a9-8f82-1ed6e5d47cd5)
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	CS0111	Type '<invalid-global-code>' already defines a member called 'Initialise' with the same parameter types	TUnit-Test	D:\sample-repo-for-tunit\TUnit-Test\obj\Debug\net9.0\TUnit.Core.SourceGenerator\TUnit.Core.SourceGenerator.CodeGenerators.TestsGenerator\Tests_TUnit_Test_TUnit-Test_0cc549a95d254c2fb74621e52114e01a.Generated.cs	13	
Error (active)	CS0116	A namespace cannot directly contain members such as fields, methods or statements	TUnit-Test	D:\sample-repo-for-tunit\TUnit-Test\obj\Debug\net9.0\TUnit.Core.SourceGenerator\TUnit.Core.SourceGenerator.CodeGenerators.TestsGenerator\Tests_TUnit_Test_TUnit-Test_0cc549a95d254c2fb74621e52114e01a.Generated.cs	17	
Error (active)	CS0111	Type '<invalid-global-code>' already defines a member called 'CollectTests' with the same parameter types	TUnit-Test	D:\sample-repo-for-tunit\TUnit-Test\obj\Debug\net9.0\TUnit.Core.SourceGenerator\TUnit.Core.SourceGenerator.CodeGenerators.TestsGenerator\Tests_TUnit_Test_TUnit-Test_0cc549a95d254c2fb74621e52114e01a.Generated.cs	17	
Error (active)	CS0111	Type '<invalid-global-code>' already defines a member called 'Tests0' with the same parameter types	TUnit-Test	D:\sample-repo-for-tunit\TUnit-Test\obj\Debug\net9.0\TUnit.Core.SourceGenerator\TUnit.Core.SourceGenerator.CodeGenerators.TestsGenerator\Tests_TUnit_Test_TUnit-Test_0cc549a95d254c2fb74621e52114e01a.Generated.cs	24	
Error (active)	CS0116	A namespace cannot directly contain members such as fields, methods or statements	TUnit-Test	D:\sample-repo-for-tunit\TUnit-Test\obj\Debug\net9.0\TUnit.Core.SourceGenerator\TUnit.Core.SourceGenerator.CodeGenerators.TestsGenerator\Tests_TUnit_Test_TUnit-Test_de79c3e32f6944edbb32af2a2205e577.Generated.cs	17	
```

**Comment by thomhurst** [comment]
Ah the compilation error was because there was a `-` in the class name which isn't valid. I've just pushed a fix to sanitize that.

After that fix, I can see discovered tests in that repo in both Rider and VS and VSCode.

Rider:
![image](https://github.com/user-attachments/assets/a30e0d7d-c033-4979-b3d2-f2760b86bb12)

VS:
![image](https://github.com/user-attachments/assets/ed184d4d-01f1-4674-806e-8d61bede6552)

VSCode (though I had to use the pre-release version?):
![image](https://github.com/user-attachments/assets/567af2b3-bbb7-4d6a-beba-43cbd401879d)

**Comment by HarryCordewener** [comment]
The new version of the Repository has the problem reproduced.
I suspect it's because of the Task not completing until Disposed - and Rider handling this situation differently from VSCode/Visual Studio somehow?

**Comment by HarryCordewener** [comment]
Unable to reproduce so far in a smaller repo. Did find that if I run in Debug mode, it runs the Tests in Visual Studio. But if I run them normally, no go. But amusingly, it misreport the time taken. The following tests took maybe like 5 minutes:
![image](https://github.com/user-attachments/assets/9bcaa996-3278-4612-85f7-954151630fb2)

**Comment by thomhurst** [comment]
Looks like it's totalling up the time of all tests. Might be an issue with the test explorer itself
