### ISSUE TITLE
Test ordering inconsistent

### ISSUE THREAD

**Issue by campersau** [thomhurst/TUnit#1033]
Using `[NotInParallel(Order = 1)]` vs. `[NotInParallel("", Order = 1)]` results in different execution orders.

`[NotInParallel(Order = 1)], [NotInParallel(Order = 2)], [NotInParallel(Order = 3)]`
- 3
- 2
- 1

Because they are executing in descending order 
https://github.com/thomhurst/TUnit/blob/ebeed9cf91a8341fe22b72f67a5e073a2e18213c/TUnit.Engine/Services/TestGrouper.cs#L13

`[NotInParallel("", Order = 1)], [NotInParallel("", Order = 2)], [NotInParallel("", Order = 3)]`
- 1
- 2
- 3

Because they are executing in ascending order
https://github.com/thomhurst/TUnit/blob/ebeed9cf91a8341fe22b72f67a5e073a2e18213c/TUnit.Engine/Services/TestsExecutor.cs#L74

According to the docs the current behavior of `[NotInParallel(Order = 1)]` is not correct:
[Orders will execute from smallest to largest. So 1 first, then 2, then 3, etc.](https://thomhurst.github.io/TUnit/docs/tutorial-extras/order)

---

How should be fix it? Currently if you have multiple classes with `[NotInParallel(Order = 1)]` they would run like this:
- A3
- B3
- A2
- B2
- A1
- B1

Should they be grouped by class instead?
- A1
- A2
- A3
- B1
- B2
- B3

**Comment by thomhurst** [comment]
> Should they be grouped by class instead?

I think that's a sensible idea. 

I imagine people using [NotInParallel] when they want to test state, so like adding/removing stuff to a database and then asserting on it. If it starts running other tests in between, then it might generate unwanted state. Probably best to run through a class first to completion.
