### ISSUE TITLE
[BUG] CancellationToken not being passed correctly

### ISSUE THREAD

**Issue by viceroypenguin** [thomhurst/TUnit#1055]
Example code:
```cs
public sealed class Dummy
{
    [Test]
    public async Task DoSomething(CancellationToken token)
    {
    }
}
```

Looks like it's not correctly paying attention to the fact that a token can be passed:
```cs
TestMethodFactory = (classInstance, cancellationToken) => AsyncConvert.Convert(() => classInstance.DoSomething()),
```

**Comment by thomhurst** [comment]
Yeah the logic is based around having a TimeoutAttribute, but the cancellation token could be cancelled for other reasons (e.g. a SIGINT) so you're right it probably makes sense to honour it if the parameter exists.

**Comment by viceroypenguin** [comment]
@thomhurst I feel like I've monopolized your time lately - thank you for your incredible work on this library; I'm so excited to be using it. I appreciate the time you're taking to answer questions and fix bugs!

**Comment by thomhurst** [comment]
No worries! I'm glad people are using it, and I appreciate the help with finding issues 😄
