### ISSUE TITLE
Is there any way we could expose the test attributes for extension?

### ISSUE THREAD

**Issue by c-schembri** [thomhurst/TUnit#1092]
Currently, attributes like `[Test]` or `[Before]` are sealed and have a base class constructor which is internal--meaning that there is no straightforward way to extend this functionality, something which, for example, NUnit allows. Allowing this kind of extensions would enable, for instance, a middle layer of user defined attributes when can then be conditionally compiled to TUnit or NUnit annotations--facilitating the usage of multiple test frameworks within one solution.

I don't fully understand the internals of the source generators, so this feature request may not be possible. Nevertheless, I am throwing it out there.

**Comment by thomhurst** [comment]
Unfortunately no, and that's due to the source generators. I need well-known compile time types to target for the generators.

If you had `MyCustomBefore`, there's no way for my source generator to know about it 😞

**Comment by thomhurst** [comment]
You could technically mix nunit and TUnit currently. They use different mechanisms under the hood - VSTest and Microsoft.Testing.Platform - So you could just select which runner to use.

**Comment by thomhurst** [comment]
Also another way to conditionally flick between the two could be global usings with compiler if statements

```csharp
#if USE_TUNIT 
global using TUnit.Core;
#else 
global using NUnit.Framework
#endif
```

That'd work for your basic test attributes. For parameterised tests you might have to using an Alias type in your using statement.
