### ISSUE TITLE
Simple unit tests are very slow compared to other frameworks

### ISSUE THREAD

**Issue by gshukov98** [thomhurst/TUnit#1120]
I want to migrate from a different unit testing framework to TUnit. I created a copy of one of my simple unit tests with TUnit, but the results were not what I expected. The unit test can be optimized from a code perspective but I didn't do it because I wanted to test the performance of the frameworks without code optimizations. Maybe I am doing something wrong it will be good if you give me feedback.

The results:
I am using Visual Studio Community 2022 Preview (17.12.0 Preview 5) I run the tests with both frameworks with .NET 8 and .NET 9 in Release.
![image](https://github.com/user-attachments/assets/51f1087e-9337-4725-866e-fa5c6584bae9)
The test projects with 'New' inside the name are with TUnit.

Old framework code:
![image](https://github.com/user-attachments/assets/e368fa83-9b52-4f25-865d-9eb22ccd4855)

TUnit code:
![image](https://github.com/user-attachments/assets/0c59a934-6e13-48cb-a4b5-477232133da3)

**Comment by thomhurst** [comment]
What's the other framework you were using?

**Comment by thomhurst** [comment]
Found it, Machine.Specifications

Your problem is that they're not reporting you a correct time.

Here's an example:

```csharp
using System.Threading;
using Machine.Specifications;

namespace Tests
{
    [Subject("Test")]
    public class When__Testing_Time
    {
        class When_Wait_5_Seconds
        {
            Because of = () => Thread.Sleep(5000);
            private It should_report_5_seconds = () => { };
        }
    }
}
```

You see I've got a 5 second `Thread.Sleep` in there.

But it's telling me it took 1ms:

![image](https://github.com/user-attachments/assets/20ff7e0e-87ed-4ac7-a6c5-728cd7c8ef84)


TUnit is giving you the accurate time.

**Comment by gshukov98** [comment]
Hmm, maybe you are right.
Thank you!
