### ISSUE TITLE
`CategoryAttribute` and `PropertyAttribute` not registered as a test trait

### ISSUE THREAD

**Issue by samtrion** [thomhurst/TUnit#1145]
Unfortunately, the current implementation is such that `CategoryAttribute` and `PropertyAttribute` are not registered as traits. This prevents, for example, the filtering of tests within Visual Studio.

**Comment by thomhurst** [comment]
I'm not sure the new testing platform has the concept of traits. I'll check in with them.

**Comment by nohwnd** [comment]
wrong window :D response here: https://github.com/microsoft/testfx/discussions/3991#discussioncomment-11153259

**Comment by thomhurst** [comment]
I think I'm a bit blocked on this, the VSTest bridge uses an internal serializable property, so I can't access it 🤔

**Comment by samtrion** [comment]
Yes, I followed the discussion at testfx. If this is resolved, I will be happy to continue with my implementation of https://github.com/dailydevops/extensions.test as a TUnit extension. I'm curious to see what other benefits TUnit will deliver

**Comment by thomhurst** [comment]
@samtrion Can you try on the latest version please?

**Comment by samtrion** [comment]
> @samtrion Can you try on the latest version please?

I'll have a look at it in the next few hours. Thanks for the quick solution 👍

**Comment by samtrion** [comment]
@thomhurst 👍 Looks good at first glance. I'll take some time over the next few days to have a closer look at custom `categories` and `properties`.
