### ISSUE TITLE
Could not find testhost

### ISSUE THREAD

**Issue by MatthewPicup** [thomhurst/TUnit#1154]
When trying to build with Visual Studio Version 17.12.0 Preview 5.0, I get the following error: Could not find testhost, and the test explorer does not populate with the tests.

When reverting to Preview 3.0, everything works correctly again.

**Comment by viceroypenguin** [comment]
I noticed that with Preview 5 that you have to go back to the settings page and re-enable the "use testing platform server mode" setting. I think there may have been a change in where that setting is stored between preview4 and preview5.

**Comment by MatthewPicup** [comment]
Awesome, thanks. Enabled that and everything is working
