### ISSUE TITLE
MethodDataSource doesn't interact well with other attributes

### ISSUE THREAD

**Issue by theodelrieu** [thomhurst/TUnit#1158]
Hello,

I'm trying to migrate our tests from xUnit to TUnit, and I'm fiddling with `MethodDataSource` to async initialize some test context.
Right now, I'm stubbling upon a Matrix test, so naturally I tried to do the following:

```csharp
    [Test]
    [MethodDataSource(nameof(CreateTestContext))]
    public async Task MyTest(MyTestContext ctx,
            [Matrix(MyEnum.Val1, MyEnum.Val2)] MyEnum firstVal,
            [Matrix(MyEnum.Val1, MyEnum.Val2)] MyEnum secondVal) {
    }
```

But the compiler screams `There is no argument given that corresponds to the required parameter [...]`.

The workaround is to write a different `CreateTestContext` and unroll the Matrix myself, which is a bit painful.
Isn't there a way to combine both `MethodDataSource` and attributes like `Matrix` or `Arguments`?

I'm no C# wizard by any stretch of the imagination, so there surely are language constraints that I'm unaware of.

**Comment by thomhurst** [comment]
Mixing different combinations together of data attributes isn't supported to generate data for a single test case.

Each data attribute will always generate a new test case.

If you want custom logic, you could implement your own data generator.

See here: https://thomhurst.github.io/TUnit/docs/tutorial-extras/data-source-generators

**Comment by thomhurst** [comment]
E.g: 

```csharp
public class MyGenerator : DataSourceGeneratorAttribute<MyTestContext, MyEnum, MyEnum>
{
    public override IEnumerable<(MyTestContext, MyEnum, MyEnum)> GenerateDataSources(DataGeneratorMetadata dataGeneratorMetadata)
    {
        foreach (var myEnum1 in Enum.GetValues<MyEnum>())
        {
            foreach (var myEnum2 in Enum.GetValues<MyEnum>())
            {
                yield return (MyClass.CreateTestContext(), myEnum1, myEnum2);
            }
        }
    }
}
```

**Comment by theodelrieu** [comment]
Thanks, I'll try it out!
