### ISSUE TITLE
System.Guid emptiness cannot be checked

### ISSUE THREAD

**Issue by theodelrieu** [thomhurst/TUnit#1172]
Hello,

When doing `await Assert.That(Guid.NewGuid()).IsNotEmpty()`, I get the following error:

```
The type 'System.Guid' cannot be used as type parameter 'TActual' in the generic type or method
'CollectionsIsNotExtensions.IsNotEmpty<TActual>(IValueSource<TActual>)'.
There is no boxing conversion from 'System.Guid' to 'System.Collections.IEnumerable'.
```

I have to call `ToString()` to workaround it, but it would be neat if it'd work out of the box.

**Comment by thomhurst** [comment]
IsNotDefault should be what you're looking for here

**Comment by theodelrieu** [comment]
Fair point, thanks.
