### ISSUE TITLE
[BUG]: `[NotInParallel]` breaks `[DependsOn]`

### ISSUE THREAD

**Issue by viceroypenguin** [thomhurst/TUnit#1176]
Check the following code:
```cs
[NotInParallel]
public sealed class Dummy
{
    [Test]
    public void Step1()
    {
        throw new NotImplementedException();
    }

    [Test]
    [DependsOn(nameof(Step1))]
    public void Step2()
    {

    }

    [Test]
    [DependsOn(nameof(Step2))]
    public void Step3()
    {

    }
}
```

Expected: `Step2` will fail since `Step1` did not succeeed.

Actual: `Step2` passes, but `Step3` fails because `Step1` has failed.

**Comment by thomhurst** [comment]
Struggling to recreate with your code. Must be some race condition or something 🤔

![image](https://github.com/user-attachments/assets/38392337-038a-41fd-bdff-59f7bdd50e54)

**Comment by viceroypenguin** [comment]
Try:
```cs
public class BaseClass;

[ClassConstructor<DummyClassConstructor>]
[NotInParallel]
public sealed class Dummy : BaseClass
{
    [Test]
    public void Step1()
    {
        throw new NotImplementedException();
    }

    [Test]
    [DependsOn(nameof(Step1))]
    public void Step2()
    {

    }

    [Test]
    [DependsOn(nameof(Step2))]
    public void Step3()
    {

    }
}

public class DummyClassConstructor : IClassConstructor
{
    public T Create<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] T>(ClassConstructorMetadata classConstructorMetadata) where T : class
    {
        if (typeof(T) != typeof(Dummy))
            throw new NotImplementedException();
        return (T)(object)new Dummy();
    }
}
```

![image](https://github.com/user-attachments/assets/a8562a27-1e2a-4a29-97b7-79542da86549)

**Comment by thomhurst** [comment]
Still the same for me! Can you confirm it still happens on 0.2.202?

**Comment by viceroypenguin** [comment]
I would, except now VS cannot run the tests; either it spends 2+ minutes trying to find tests before I cancel it, or it runs Step1/Step2 and never completes either of them. I can confirm that running the project under 0.2.195 gave me two fails and one pass, while 0.2.202 gives me three fails, as expected.

**Comment by thomhurst** [comment]
The latest version has broken Visual Studio for you?

**Comment by viceroypenguin** [comment]
> The latest version has broken Visual Studio for you?

Yes. Was fine under 0.2.195, broken on 0.2.202

**Comment by thomhurst** [comment]
@viceroypenguin Can you reproduce it? My test explorer is working fine on the latest version.

**Comment by viceroypenguin** [comment]
Yes. This is what happens currently in VS 17.12 preview 5:
![image](https://github.com/user-attachments/assets/69c52075-089b-48c0-856c-1e417a6cf3a8)

**Comment by viceroypenguin** [comment]
![image](https://github.com/user-attachments/assets/1fdd1da4-6ce5-4a23-b2ef-a9360e1bdd95)

**Comment by thomhurst** [comment]
Can you try 0.2.208?

**Comment by viceroypenguin** [comment]
Yes, 0.2.208 works correctly. Thanks!
