### ISSUE TITLE
`After(Assembly)` not being called

### ISSUE THREAD

**Issue by ledjon-behluli** [thomhurst/TUnit#1206]
Given something like this:

```
public static class GlobalEntry
{
    private static GlobalInitializer _initializer = new();

    static GlobalEntry()
    {
#if DEBUG
        Environment.SetEnvironmentVariable(TestConstants.ENV_VAR_REUSE_CONTAINERS, "1");
        Environment.SetEnvironmentVariable(TestConstants.ENV_VAR_USE_LOCAL_COSMOS_EMULATOR, "1");
#endif
    }

    [Before(Assembly)]
    public static async Task SetUp() => await _initializer.InitializeAsync();

    [After(Assembly)]
    public static async Task TearDown() => await _initializer.DisposeAsync();
}
```

I can hit a breakpoint on `SetUp` when running under the debugger, but `TearDown` is never hit. When I use `Before/After(TestSession)` both breakpoints are hit.

If I test this in a small repro, it does hit the breakpoint and it works, but not in my app. 

I would be pleased to provide you more information, but I currently have no idea on what infos to even provide as this is my first time trying out this project. I figured you may have better questions than me having better infos to provide (if that makes sense).

Please feel free to ask

**Comment by thomhurst** [comment]
Any exceptions?

How many tests in your test suite?

Admittedly this is going to be hard to fix without a repro.

**Comment by ledjon-behluli** [comment]
@thomhurst no exceptions, roughly 35 tests split into 5 test classes, all parallel

**Comment by thomhurst** [comment]
Would you be able to copy your test suite, strip out any sensitive logic/code and see if it still happens? And then if so push it as a repo that I can clone?

**Comment by ledjon-behluli** [comment]
That is gonna be quite challenging, but i'll be in the lookout for what might be the problem.
The fact that `TestSession` works is great and bad at the same time. Great because I can do with it and it resolves the problem.
Bad because the incentive to dig deeper isn't there. But if i find out something i'll come back to this. Just thought if you had an idea. Thanks

I am going to close this for now, and if I find something I'll reopen @thomhurst

**Comment by thomhurst** [comment]
@ledjon-behluli Did you skip any tests out of curiosity?

**Comment by thomhurst** [comment]
Could you try on v0.3.20? I've made some changes

**Comment by ledjon-behluli** [comment]
@thomhurst i did! Imma give it a go later on

**Comment by ledjon-behluli** [comment]
@thomhurst tried it with v `0.3.31`, `After(Assembly)` is being called now :)

**Comment by thomhurst** [comment]
Brill! Yeah it was because skipped tests weren't being counted properly, but they are now :)
