### ISSUE TITLE
[question] How to skip specific folders when running from top-level directory?

### ISSUE THREAD

**Issue by theodelrieu** [thomhurst/TUnit#1209]
Hello,

I couldn't find the answer in the docs, so here I am.
Before migrating to TUnit, all I had to do with xUnit was running `dotnet test` from my top-level directory.
Some of my test projects have the attribute `IsTestProject` set to false. This is to avoid running them everytime, as they are quite heavy and require specific configuration, so they have their own CI job.

Unfortunately, `IsTestProject` doesn't seem to be handled by TUnit. Is there a way to ignore specific folders?

**Comment by thomhurst** [comment]
How are you running them separately if they're not considered test projects?

You could try `<TestingPlatformDotnetTestSupport>false</TestingPlatformDotnetTestSupport>` ?

**Comment by theodelrieu** [comment]
I'm currently toggling `-p:IsTestProject=true` in specific CI jobs.

Doing the same with `TestingPlatformDotnetTestSupport` seems to work, thanks!
