### ISSUE TITLE
[question] How to properly log?

### ISSUE THREAD

**Issue by theodelrieu** [thomhurst/TUnit#1249]
Hello,

I had to remove every instance of `ITestOutputHelper` when migrating from xUnit to TUnit, but I couldn't find anything in the doc about logging.

Looking at the code, there are some logging-related classes in `TUnit.Engine.Logging`. Are they supposed to be used by client code? Is `Console.WriteLine` the way to go?

**Comment by thomhurst** [comment]
Yep console writelines are automatically intercepted by the framework

**Comment by theodelrieu** [comment]
Thanks. It's still not clear to me what the difference between [xUnit](https://xunit.net/docs/capturing-output) and TUnit is on that aspect. Are there missing/added features?

EDIT: We currently have a lot of Asp services that take an `ILogger`, so I'd like to get an ILogger in my tests like I'm able to do with xUnit, c.f. [this article](https://blog.martincostello.com/writing-logs-to-xunit-test-output/).

**Comment by thomhurst** [comment]
If you wanted an ILogger you'd have to create your own implementation, because TUnit doesn't have any dependencies on Microsoft.Extensions.Logging.

You can get a TUnitLogger by doing `TestContext.Current!.GetDefaultLogger()` - so your custom ILogger could forward calls on to the TUnit logger

**Comment by theodelrieu** [comment]
Thanks!
