### ISSUE TITLE
Error stack trace issue with v0.3.34

### ISSUE THREAD

**Issue by jacob7395** [thomhurst/TUnit#1263]
Hey, 

When I run the same test on 0.3.34 I get this;

![image](https://github.com/user-attachments/assets/fd65d996-cd7a-4c4f-bfac-7a3ae88402df)

When running from the console the stack trace is still there.

I downgraded to 0.3.0 and for the same test as above I get;

![Screenshot 2024-11-21 143653](https://github.com/user-attachments/assets/a2648bfa-99dd-4905-8b07-a5e6fc00a085)

Don't see another issue for this, I am using Rider and have tried on Linux and two windows computers.

**Comment by thomhurst** [comment]
Should be fixed in 0.3.43

**Comment by jacob7395** [comment]
Appears to work as expected now, thanks 👍
