### ISSUE TITLE
How to use TUnit to test a source generator?

### ISSUE THREAD

**Issue by AnderssonPeter** [thomhurst/TUnit#1295]
Hi first of thanks for a cool project, so far it works great!

I'm writing a `Source Generator` and was wondering if there is any support for testing them using `TUnit`?

From what I have found there are nugets for the other big unit testing frameworks:
* `Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.MSTest`
* `Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.NUnit`
* `Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.XUnit`

Are there any plans to add `Microsoft.CodeAnalysis.CSharp.SourceGenerators.Testing.TUnit`?

**Comment by AnderssonPeter** [comment]
Sorry for posting this, it seems the recommendation is to use `Microsoft.CodeAnalysis.CSharp.Analyzer.Testing` instead, and my guess is that it should work with TUnit :)

**Comment by viceroypenguin** [comment]
The engine specific versions are no longer maintained. Use the generic one, v1.1.2 and up. You can see an example using the TUnit engine here: https://github.com/ImmediatePlatform/Immediate.Handlers
