### ISSUE TITLE
TryParse hangs on invalid input

### ISSUE THREAD

**Issue by koddek** [thomhurst/TUnit#1304]
The TryParse method fails with invalid input, causing the test to hang indefinitely. When executed concurrently with other tests, the one containing the TryParse with invalid input stalls the rest. However, if this particular test is omitted, the entire suite of tests completes successfully.

Here are three examples of similar tests for your reference. The first test is the one experiencing the issue. Additionally, I have provided the source for the AccountId. I am using a MacBook Air with an M1 chip.

```cs
// This test continues indefinitely without finishing (hangs)
// and, depending on the number of tests in the class, it causes other tests to wait
[Test]
[Arguments("\"2c48c152-7cb7-4f51-8f01-704454f36e60\"")]
[Arguments("invalidNotAGui")]
[Arguments("")]
[Arguments(" ")]
[Arguments(null)]
public async Task TryParse_InvalidString_ReturnsFailure(string? input)
{
    // Act
    bool success = AccountId.TryParse(input, out var id);

    // Assert
    await Assert.That(success).IsFalse();
    await Assert.That(id).IsNull();
}

// This tests works fine
[Test]
[Arguments("\"2c48c152-7cb7-4f51-8f01-704454f36e60\"")]
[Arguments("invalidNotAGui")]
[Arguments("")]
[Arguments(" ")]
[Arguments(null)]
public async Task Parse_InvalidString_ThrowsException(string? input)
{
    await Assert.That(() => AccountId.Parse(input)).ThrowsException();
}

// This test works fine
[Test]
[Arguments("2c48c152-7cb7-4f51-8f01-704454f36e60")]
[Arguments("00000000-0000-0000-0000-000000000000")]
public async Task TryParse_ValidString_ReturnsAccountId(string input)
{
    // Act
    bool success = AccountId.TryParse(input, out var id);

    // Assert
    //using var _ = Assert.Multiple();
    await Assert.That(success).IsTrue();
    await Assert.That(id.ToString()).IsEqualTo(input);
}

// this is the account id's code
[ValueObject<Guid>]
public readonly partial record struct AccountId : IIdentifiable<AccountId>
{
    public bool HasValue => _value != Guid.Empty;

    public static AccountId Empty => From(Guid.Empty);

    /// <summary>
    /// Builds a new ID from a new <see cref="Guid"/> version 7
    /// </summary>
    public static AccountId New => From(Guid.CreateVersion7());
}

public interface IIdentifiable<out TId>
{
    bool HasValue { get; }
    static abstract TId Empty { get; }
    static abstract TId New { get; }
}
```

**Comment by thomhurst** [comment]
This looks to be an issue with Vogen, I can replicate it in a standard Console application.

Raised here: 

https://github.com/SteveDunn/Vogen/issues/716

**Comment by koddek** [comment]
I am sorry. Working late caused me to miss this. I guess the issue can be closed. Thanks for opening an issue on Vogen.
Additionally, maybe tests should be designed to run independently rather than waiting on others, as is currently the case. This approach would prevent a single crash from hindering the completion of other functioning tests.

**Comment by thomhurst** [comment]
@koddek  You should get better feedback on v0.4.14

**Comment by koddek** [comment]
Tested v0.4.14.
All tests have run to completion now, except for this one.
You move quickly—thank you, and great work!
