### ISSUE TITLE
Icon needed :)

### ISSUE THREAD

**Issue by agray** [thomhurst/TUnit#1308]
Suggest you need an icon for TUnit like NUnit and XUnit.

**Comment by thomhurst** [comment]
Yeah I need a designer haha

**Comment by agray** [comment]
I used a stock image and the product icons for Saucery and Saucery.XUnit.

Need your product icon for a Saucery.TUnit  😄

**Comment by vbreuss** [comment]
Maybe also move the repo to a dedicated GitHub organization?

**Comment by agray** [comment]
I suggest your logo should be just this:

![image](https://github.com/user-attachments/assets/677f9913-a6a0-47eb-a5ca-d5248ce2efc5)

Looks better imo. More like NUnit and XUnit:

![NUnit](https://github.com/user-attachments/assets/19967d71-91ec-430e-b4ff-87588a9b71c0)
![image](https://github.com/user-attachments/assets/e2b19994-7b0c-454e-8890-e4847c783bb2)

My Logo is 

![image](https://github.com/user-attachments/assets/b868f2b8-ff56-4840-9a37-bf774a3f1dc8)

https://github.com/Sauceforge/Saucery
