### ISSUE TITLE
IsEquivalentTo says there are differences between two identical objects?

### ISSUE THREAD

**Issue by AnderssonPeter** [thomhurst/TUnit#1315]
Hi I'm writing a unit test for a source generator, where I have a `Model` class that contains the information about a Parsed class.

I'm using TUnit to run my unit tests, and it works great!
But it seems `IsEquivalentTo` yields a incorrect error (or at least I think it does)

All the classes/structuts/records implement `GetHashCode` and `Equals` (most of them are records, so I get it for free).

The error happens on [here](https://github.com/AnderssonPeter/Dolly/blob/eedbfcc7030aab3becb28974fd871e5d5a1739c1/Dolly.Tests/GeneratorTests.cs#L53)
And yields the error: 
```
Expected model to be equivalent to expected

but Property Members did not match
Expected: [Member { Name = First, IsReadonly = False, Flags = None, IsEnumerable = False, IsClonable = False, IsNewCompatible = False, IsMemberNullable = False, IsElementNullable = False }, Member { Name = Second, IsReadonly = False, Flags = None, IsEnumerable = False, IsClonable = False, IsNewCompatible = False, IsMemberNullable = False, IsElementNullable = False }]
Received: [Member { Name = First, IsReadonly = False, Flags = None, IsEnumerable = False, IsClonable = False, IsNewCompatible = False, IsMemberNullable = False, IsElementNullable = False }, Member { Name = Second, IsReadonly = False, Flags = None, IsEnumerable = False, IsClonable = False, IsNewCompatible = False, IsMemberNullable = False, IsElementNullable = False }]

at Assert.That(model).IsEquivalentTo(expected)
```

From what I can see the text is identical in the error.
And if I run `model.Equals(expected)` it returns `true`.

If I switch to `IsEquatableOrEqualTo` instead it works as expected. So you don't have to fix the issue just for me but I wanted to report it.

Edit: I have also checked that the HashCodes of both objects are identical.

**Comment by AnderssonPeter** [comment]
@thomhurst That was fast!! 💨

**Comment by thomhurst** [comment]
Haha thanks I do try 😆 

Version 0.4.31 should be out in 5-10 minutes if you want to give that a try

**Comment by AnderssonPeter** [comment]
It worked, thanks for the fast fix :)
