### ISSUE TITLE
Exceptions after a failed assertion in `Assert.Multiple()` are swallowed

### ISSUE THREAD

**Issue by afscrome** [thomhurst/TUnit#1334]
Assert.Multiple seems to hide exceptions that occur after the first failed assertion
```cs
    [Test]
    public async Task Test()
    {
        using (Assert.Multiple())
        {
            await Assert.That(1).IsEqualTo(2);
            await Assert.That(2).IsEqualTo(4);
            throw new Exception("Hello World");
            await Assert.That(3).IsEqualTo(6);
        }
    }
```

There is no mention of the "Hello World" exception anywhere in the test error.  Combined with the message only listing 2 assertion failures, makes it look like the 3rd assertion passed.

```
 Message: 
One or more errors occurred. (Expected 1 to be equal to 2

but found 1

at Assert.That(1).IsEqualTo(2)) (Expected 2 to be equal to 4

but found 2

at Assert.That(2).IsEqualTo(4))

  Stack Trace: 
AssertionScope.Dispose()
ManualCredentialTypeTests.Foo2() line 24
AsyncConvert.Convert(Func`1 action)
DiscoveredTest`1.ExecuteTest(CancellationToken cancellationToken)
Timings.Record(String name, TestContext context, Func`1 action)
TestInvoker.Invoke(DiscoveredTest discoveredTest, CancellationToken cancellationToken, List`1 cleanupExceptions)
TestInvoker.Invoke(DiscoveredTest discoveredTest, CancellationToken cancellationToken, List`1 cleanupExceptions)
SingleTestExecutor.ExecuteTestMethodWithTimeout(DiscoveredTest discoveredTest, CancellationToken cancellationToken, List`1 cleanupExceptions)
SingleTestExecutor.ExecuteWithCancellationTokens(DiscoveredTest discoveredTest, List`1 cleanupExceptions)
SingleTestExecutor.ExecuteWithRetries(DiscoveredTest discoveredTest, List`1 cleanupExceptions)
SingleTestExecutor.ExecuteWithRetries(DiscoveredTest discoveredTest, List`1 cleanupExceptions)
SingleTestExecutor.ExecuteTestInternalAsync(DiscoveredTest test, ITestExecutionFilter filter, ExecuteRequestContext context, Boolean isStartedAsDependencyForAnotherTest)
SingleTestExecutor.ExecuteTestInternalAsync(DiscoveredTest test, ITestExecutionFilter filter, ExecuteRequestContext context, Boolean isStartedAsDependencyForAnotherTest)
SingleTestExecutor.ExecuteTestInternalAsync(DiscoveredTest test, ITestExecutionFilter filter, ExecuteRequestContext context, Boolean isStartedAsDependencyForAnotherTest)
TestsExecutor.ProcessTest(DiscoveredTest test, ITestExecutionFilter filter, ExecuteRequestContext context, CancellationToken cancellationToken)
```

This only happens if there is at least one failure before the exception occurs - the following will include the exception that occured

```cs
        using (Assert.Multiple())
        {
            await Assert.That(1).IsEqualTo(1);
            throw new Exception("Hello World");
            await Assert.That(3).IsEqualTo(6);
        }
```

If an exception occurs within `Assert.Multiple()`, I'd like to see the exception within the multiple assertion failure.  It would also be nice to see some kind of a `1 of 2 assertions failed` text from Assert.Multiple() - that would also give you a better chance of differentiating between  "The unmentioned assertions passed" and "The unmentioned assertions weren't run"

**Comment by thomhurst** [comment]
As for displaying the exception - I'm not sure I can do this without converting from a using scope to a delegate input.

Because the assertions are in a scope, and not a delegate, TUnit.Assertions doesn't have any control over the execution of that code. TUnit.Assertions isn't executing that `throw new Exception` - And so I can't catch it and grab a reference to it.

Unless you have any clever ideas, I would just keep assert multiple scopes to only executing assertion code.

As for the `1 of 2 assertions failed`, that seems like a sensible idea.

**Comment by afscrome** [comment]
Yea, I agree you should avoid Exceptions if you can, but there are certain ones (e.g. `NullReferenceException`) you can still introduce unintentionally.

The original context for this issue was trying to work out why it seemed like the first assertion below passed, but the second failed, which seemed impossible, when it actually was failing with a null reference exception.

```cs
        using (Assert.Multiple())
        {
            await Assert.That(foo).IsNotNull();
            await Assert.That(foo.Bar).IsNotNull();
        }
```

As the error initially read to me that the first assertion failed, but the second passed, which seemed like an impossible combination!!!

```
Message: 
Expected foo to not be null

but it was

at Assert.That(foo).IsNotNull()
```

There is https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getexceptionpointers?view=net-8.0 which is used by `Activity` to detect errors.  I don't see how to get the actual exception from that, but it could be enough to avoid having `Assert.Multiple` throw it's exception to let the original one bubble out.  Also looks like this may not work on all platforms (in particular mono & NativeAOT - https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-dotnet%20GetExceptionPointers&type=code ) so it's probably still worth including the total assertion count to help give an indication that not all assertions ran on platforms without `GetExceptionPointers`.

**Comment by thomhurst** [comment]
That pointer didn't work - Doesn't seem to be a way to convert it to a managed object.

But I've found a nicer solution actually - Just utilising AppDomain events to intercept exceptions 😁

**Comment by thomhurst** [comment]
v0.4.54 should be out if you wanna give that a go
