### ISSUE TITLE
Test Class Not Executing as Expected

### ISSUE THREAD

**Issue by agray** [thomhurst/TUnit#1368]
If I create a class with the single test its discoverable (it can be seen in the Test Explorer) and executable:

```
public class ClickLinkTests()
{
    [Test]
    public async Task ClickLinkTest()
    {
        //My Test Code...
    }
}
```

But if I make that class a subclass and add a MethodDataSource attribute it is no longer discoverable.

```
public class ClickLinkTests() : SauceryTBase
{
    [Test]
    [MethodDataSource(typeof(RequestedPlatformData), nameof(RequestedPlatformData.AllPlatforms))]
    public async Task ClickLinkTest(BrowserVersion requestedPlatform)
    {
        //My Test Code...
    }
}
```

Using TUnit 0.4.83

EDIT:
Subsequently got discoverability (with a List<Func<>>) but ParallelLimiter seems to be failing after the first batch. Limiting the parallel batches is important in my context cause SauceLabs accounts have parallel test limits, so the test driver needs to restfully check SauceLabs for available headroom and feed in tests in a controlled manner.

**Comment by thomhurst** [comment]
Can you try v0.4.83?

**Comment by agray** [comment]
Kinda works with TUnit 0.4.74 but not really. No better or worse with v83.

Had hoped ParallelLimiter would make it work. It did a little but now tests are hanging after the first batch. 2 of the first batch failed on SauceLabs due to command time out after 90 seconds.

TUnit is just hanging it seems:

![image](https://github.com/user-attachments/assets/ac015263-4a4e-4f71-9ffe-c38f98d5457a)

And this is all SauceLabs received from TUnit:
![image](https://github.com/user-attachments/assets/5092f389-12a4-4f8b-86fd-3617e9f713ee)


I don't have this problem with NUnit and XUnit integration with SauceLabs.

**Comment by thomhurst** [comment]
What does your parallel limiter look like and how are you setting it?

**Comment by agray** [comment]
Have a look at these:
https://github.com/Sauceforge/Saucery/tree/master/Merlin.TUnit
https://github.com/Sauceforge/Saucery/tree/master/Saucery.TUnit

**Comment by agray** [comment]
TUnit has some really nice features.  Must be something I haven't quite done right.

The DataDrivenTest.cs is not currently being discovered by TUnit

**Comment by thomhurst** [comment]
I'll try and clone and take a look when I get some time

**Comment by agray** [comment]
> I'll try and clone and take a look when I get some time

You'll need a trial SauceLabs account to use Saucery.

**Comment by thomhurst** [comment]
> The DataDrivenTest.cs is not currently being discovered by TUnit

It is but it's failing initialization. Because your test data is throwing an exception. `BrowserVersions` is null and you're trying to do a LINQ query on it:

![image](https://github.com/user-attachments/assets/ce6a1058-ed6e-4ba1-a19e-deb73028ee66)

**Comment by agray** [comment]
Let me check when I have time and I'll report back

**Comment by thomhurst** [comment]
Is this sorted now?
