### ISSUE TITLE
Unclear names of tests with Method Data Sources

### ISSUE THREAD

**Issue by Barsonax** [thomhurst/TUnit#1374]
I noticed that the name of tests that use method data sources are not very clear. It seems to just use the parameter type name with no way to change it which means all the tests are named the same which makes it hard to find the one you are looking for.

```cs
[DebuggerDisplay("foobar")]
public record AdditionTestData(int Value1, int Value2, int ExpectedResult)
{
    public override string ToString() => "blabla";
};

public static class MyTestDataSources
{
    public static IEnumerable<Func<AdditionTestData>> AdditionTestData()
    {
        yield return () => new AdditionTestData(1, 2, 3);
        yield return () => new AdditionTestData(2, 2, 4);
        yield return () => new AdditionTestData(5, 5, 10);
    }
}

public class MyTestClass
{
    [Test]
    [MethodDataSource(typeof(MyTestDataSources), nameof(MyTestDataSources.AdditionTestData))]
    public async Task MyTest(AdditionTestData additionTestData)
    {
        var result = Add(additionTestData.Value1, additionTestData.Value2);

        await Assert.That(result).IsEqualTo(additionTestData.ExpectedResult);
    }

    private int Add(int x, int y)
    {
        return x + y;
    }
}
```

![image](https://github.com/user-attachments/assets/bc308f48-5c1d-4596-b8e8-491b15157a0d)

I tried overriding tostring and using debuggerdisplay but that does not seem to have any effect. 

I think it would be nice if TUnit would use ToString or DebuggerDisplay or provide some other way to show a meaningful name of a parameterized test.

**Comment by thomhurst** [comment]
I need to add some docs on this, but you should be able to implement your own formatter and register it with this attribute: https://github.com/thomhurst/TUnit/blob/239cb15b56020ff8be9759366b612ef72d0c6bcf/TUnit.Core/Attributes/TestData/ArgumentDisplayFormatterAttribute.cs#L16

**Comment by thomhurst** [comment]
You tell it what types you can format, and then how to format them

**Comment by Rick-van-Dam** [comment]
Cool that even this is configurable!

Would it make sense though to change the default to use ToString? I think the current default to take the type name is not what most ppl would want.

**Comment by thomhurst** [comment]
Yeah probably a good shout. I'll do some experimenting and will see how it feels. Happy to switch it over if it feels natural
