### ISSUE TITLE
Class parameterized tests don't show "play" buttons in Rider on Linux

### ISSUE THREAD

**Issue by BenjaBobs** [thomhurst/TUnit#1388]
I'm not sure if this issue belongs here or in YouTrack ([x-post](https://youtrack.jetbrains.com/issue/RIDER-120992/Play-buttons-not-showing-up-for-class-parameterized-tests-in-TUnit-new-testing-platform)) for Rider, or in some Microsoft github for Testing Platform, so I'm posting it both places for visibility, and we can close it here if it doesn't belong. :)

### Class parameterized tests don't show "play" buttons in Rider

![image](https://github.com/user-attachments/assets/038ba786-6b90-4412-8e33-2197ed41c96e)

![image](https://github.com/user-attachments/assets/86b9d491-7cd1-431d-9494-4d8d8f7c6d8f)

They still work though, and show up in the test explorer, so it's more of a nuisance than a blocker.

**Comment by thomhurst** [comment]
Yeah it'll be a rider issue. If the tests are discovered and runnable, TUnit has done it's bits, so up to the IDE after that

**Comment by BenjaBobs** [comment]
Alright, thanks for clarifying.
I'll close this issue then. :slightly_smiling_face:
