### ISSUE TITLE
TUnit output

### ISSUE THREAD

**Issue by Dejavu333** [thomhurst/TUnit#1420]
If I'm running a while loop in a [Test] then I get the following output to terminal which pollutes my logs, and it can't be disabled with --verbosity minimal.

  [+0/x0/?0] botTest.TUnit.dll (net8.0|x64)(6s)

  [+0/x0/?0] botTest.TUnit.dll (net8.0|x64)(9s)

  [+0/x0/?0] botTest.TUnit.dll (net8.0|x64)(12s)

  [+0/x0/?0] botTest.TUnit.dll (net8.0|x64)(15s)

  [+0/x0/?0] botTest.TUnit.dll (net8.0|x64)(18s)

## Example code:

 _while (true)
{
     System.Console.WriteLine("something");
    await Task.Delay(100);
}_

**Comment by thomhurst** [comment]
This is part of the Microsoft Testing Platform. You'll want to raise it on here: https://github.com/microsoft/testfx
