### ISSUE TITLE
.NET Standard 2.0 target should avoid a System.Text.Json 9.0.0 dependency

### ISSUE THREAD

**Issue by AArnott** [thomhurst/TUnit#1460]
The package dependency only shows up in the netstandard2.0 target framework anyway, and by referencing 9.0.0, even .NET 8 test projects were required to reference STJ 9 rather than the one that comes with the runtime.
Given tests should be testing the library in their natural environment, we should avoid forcing a test to update dependencies beyond what the library under test would naturally require.

Referencing STJ 9 is fine once .NET 9 is the oldest supported runtime by Microsoft (in about a year).

**Comment by viceroypenguin** [comment]
Nit: net9 will never be the oldest supported framework. Net8 support will continue until net11 is released.

**Comment by thomhurst** [comment]
Are these libraries actually tightly coupled to the .NET version? If it's only in .net standard anyway it won't be affecting net core runtimes.

**Comment by viceroypenguin** [comment]
> Are these libraries actually tightly coupled to the .NET version? If it's only in .net standard anyway it won't be affecting net core runtimes.

Correct. STJ is not considered tightly coupled to the net sdk, and developers are encouraged to use newer STJ versions with older sdk.

**Comment by AArnott** [comment]
> If it's only in .net standard anyway it won't be affecting net core runtimes.

It does, actually.
Consider a .NET Standard 2.0 library that consumes this one. It now requires STJ 9.
Now a .NET 8 application project comes along and references the .NET Standard 2.0 library. Now that .NET 8 app must ship STJ 9, instead of relying on the one that .NET 8 ships. This makes the app larger. It also increases the servicing onus on the app author because now the (relatively regular) servicing updates to STJ have to ship in new app servicing releases instead of just when the app user keeps their .NET 8 runtime current.

**Comment by viceroypenguin** [comment]
> It also increases the servicing onus on the app author because now the (relatively regular) servicing updates to STJ have to ship in new app servicing releases instead of just when the app user keeps their .NET 8 runtime current.

I'm not sure what you mean here, since both net8 and net9 have monthly servicing releases, and STJ follows the SDK release schedule.

**Comment by AArnott** [comment]
@viceroypenguin A .NET 8 app that does _not_ ship System.Text.Json.dll (because it uses v8 which is included in the runtime) has no servicing responsibility for that dll, because the user that installed the app is responsible to keep their runtime updated.

In contrast, a .NET 8 app that _does_ ship System.Text.Json.dll v9 now has to service the app itself to update the STJv9 DLL whenever a security vulnerability is found in it.
And it makes the app larger.

I'm assuming a FDD (framework-dependent deployment) app here. If it's an SCD (self-contained deployment) app which includes the runtime, then there's a servicing onus either way.

**Comment by AArnott** [comment]
This regressed. Please reopen, @thomhurst.
