### ISSUE TITLE
CS0229 ambiguity because `HookType` enum values coming into scope by default

### ISSUE THREAD

**Issue by AArnott** [thomhurst/TUnit#1463]
When adding `TUnit.Engine` as a package reference, I get a CS0229 compile error in two places where I reference the .NET `Assembly` type:

> Ambiguity between 'HookType.Assembly' and 'Assembly'

In fact _all_ values from the `TUnit.Core.HookType` are in scope, meaning I can reference all values without prefixing with `HookType.`, as if a `using static TUnit.Core.HookType` were at the type of my source file. But since there _isn't_ such an entry in my code file, I can only imagine there is a `global using static TUnit.Core.HookType` in another file, possibly generated by a source generator or adding as an msbuild `<Using>` element by an imported props file.

Anyway, it seems inappropriate and is certainly a pain. Can this package be altered to remove that global using?

![image](https://github.com/user-attachments/assets/4e329ddb-00c9-4068-b2ad-b71e4436b970)

**Comment by AArnott** [comment]
...and there it is:

![image](https://github.com/user-attachments/assets/db03b3d9-0fff-48e2-b06c-75aa213881a1)

So apparently I can turn it off, but why does the default include such an odd using?

**Comment by thomhurst** [comment]
> ...and there it is:
> 
> ![image](https://private-user-images.githubusercontent.com/3548/398752206-db03b3d9-0fff-48e2-b06c-75aa213881a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMjYwNTgsIm5iZiI6MTczNTIyNTc1OCwicGF0aCI6Ii8zNTQ4LzM5ODc1MjIwNi1kYjAzYjNkOS0wZmZmLTQ4ZTItYjA2Yy03NWFhMjEzODgxYTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjZUMTUwOTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGNlMzFkYjJmZjlkMzQyNTc0ODg5YzlmZTUzNzVhOGE3MTQ2YjIyMjYxOGUzZmU4NWUzYzhmMjQ0MDkxOTVkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2ca81_hStL2tIURwcyxzBaG1eHN0Ly9v2IDVv1kY9us)
> 
> So apparently I can turn it off, but why does the default include such an odd using?

To make the code read nicer. [Before(Test)] and [Before(Assembly)] etc.

I don't plan on changing this. The people that need to start doing custom assembly or type loading logic will be the minority. And switching it off or using fully qualified namespaces in the type works around it.

Happy to accept any doc updates though to make this clearer.

**Comment by AArnott** [comment]
Alright. Thanks for the consideration and fast response.

**Comment by jnm2** [comment]
What I wanted to use was just `Assembly.GetExecutingAssembly().GetName().Name`, and it was jarring figuring out what was going on. No custom loading logic, just an API off `System.Reflection.Assembly`.

Once my [target-typed static member access](https://github.com/dotnet/csharplang/discussions/9078) proposal comes to fruition, it will be idiomatic to write `[Before(.Test)]` and `[Before(.Assembly)]`, and this global static using could be dropped.
