### ISSUE TITLE
Test Discovery not working in JetBrains Rider macOS

### ISSUE THREAD

**Issue by koddek** [thomhurst/TUnit#1469]
Test discovery have not been working with any TUnit version above 0.5.18 on Rider, on MacOS, even with Rider 2024.3.3

**Comment by vfrz** [comment]
I'm having the same issue on Linux after upgrading from 0.5.18 to 0.5.22
So I believe this is caused by one of these two commits:
https://github.com/thomhurst/TUnit/commit/6bf73fd331df76d520669bdecc44e86d7c03cc26
https://github.com/thomhurst/TUnit/commit/668c1cfb57ac1598acff2fc897815f6a3c4a3045

**Comment by thomhurst** [comment]
> I'm having the same issue on Linux after upgrading from 0.5.18 to 0.5.22 So I believe this is caused by one of these two commits: [6bf73fd](https://github.com/thomhurst/TUnit/commit/6bf73fd331df76d520669bdecc44e86d7c03cc26) [668c1cf](https://github.com/thomhurst/TUnit/commit/668c1cfb57ac1598acff2fc897815f6a3c4a3045)

It's most likely upgrading the Microsoft.Testing.Platform to 1.5.0.

As to why that's broken things though... I don't know. Visual studio seems fine so seems isolated to Rider

**Comment by thomhurst** [comment]
I've had to downgrade the testing platform package for now to get this working again. But Rider discovery should be working in TUnit 0.6.14 and Rider 2024.3.3. I'll raise an issue with them about the latest testing platform package breaking discovery.

**Comment by vfrz** [comment]
Alright, thanks! 
People have already commented about this regression on the previous issue here: https://youtrack.jetbrains.com/issue/RIDER-117732/Enable-Testing-Platform-support-doesnt-display-any-unit-tests-from-TUnit-on-macOS-and-Linux

**Comment by thomhurst** [comment]
Cheers, I've raised a more specific issue: https://youtrack.jetbrains.com/issue/RIDER-121484/Package-Microsoft.Testing.Platform.MSBuild-1.5.0-breaks-test-discovery
