### ISSUE TITLE
[Doc]Add in the home page full AOT support feature

### ISSUE THREAD

**Issue by MarcoRossignoli** [thomhurst/TUnit#400]
here https://thomhurst.github.io/TUnit/

I would say "loudly" that the adapter support or is designed to work full native AOT/Single file in home page.

It's pretty unique feature for a testing framework, at the moment at least.

**Comment by thomhurst** [comment]
Good shout! I haven't actually managed to add the Single File testing into my pipeline yet though due to https://github.com/microsoft/testfx/issues/3758

**Comment by thomhurst** [comment]
All done now 😄
