### ISSUE TITLE
Output Messages

### ISSUE THREAD

**Issue by biqas** [thomhurst/TUnit#525]
Hi,

How to inject logging into tests? or write to output window or any output sink?

**Comment by thomhurst** [comment]
Hi @biqas - If you're executing using `dotnet run` then Console output should display normally.

If you're using Visual Studio, I think they're still working on showing the Console output in each test results window.

If you want to dynamically retrieve a tests output, you could register a global `[AfterEvery(Test)]` method.

E.g.

```csharp
    [AfterEvery(Test)]
    public static async Task TestOutput(TestContext context)
    {
        var output = context.GetTestOutput();
        var errorOutput = context.GetTestErrorOutput();
        
        // Do something with `output` or `errorOutput` 
    }
```

Does that solve your problem?

**Comment by biqas** [comment]
Hi,

to get the output yes, but i would like to redirect the logger output to the test output. This is in some complex cases needed to see how far a test came along to look at the logs in the test output.

**Comment by thomhurst** [comment]
I don't quite understand what you mean by "logger output to test output"? Are you talking about the visual studio results window?

If not, can you give an equivalent example in xUnit or NUnit?

**Comment by biqas** [comment]
Something like this:

```csharp
public MyTest(ITestOutputHelper output, LogLevel logLevel = LogLevel.Debug)
{
    Logger = output.BuildLogger(logLevel, GetType().Name);
}
```

ITestOutputHelper is from xUnit. This redirects all ILogger messages to the output of the unit test. To achieve this there is an extension needed (Neovolve.Logging.Xunit).

**Comment by thomhurst** [comment]
@biqas You can do `Logger = new DefaultLogger()` for a logger that writes to the console.
Otherwise you can define your own class that inherits from `TUnitLogger` and then define your own logging implementation.

Does that help?

**Comment by david-driscoll** [comment]
I think the big thing that @biqas is after (and myself as well) is the ability to log and capture logs for a given test and provide that as output similar to how xunit has the `ITestOutputHelper`.

It's very close to how `OutputWriter` and `ErrorOutputWriter` are working with the test context.  The only issue is that the log information is not available in the the IDE when you're inspecting a given test.

**Comment by thomhurst** [comment]
> I think the big thing that @biqas is after (and myself as well) is the ability to log and capture logs for a given test and provide that as output similar to how xunit has the `ITestOutputHelper`.
> 
> It's very close to how `OutputWriter` and `ErrorOutputWriter` are working with the test context. The only issue is that the log information is not available in the the IDE when you're inspecting a given test.

When TUnit finishes a test it sends all the relevant error / standard output to the runner. So I believe not seeing the output is a current limitation of the new Microsoft testing framework (correct me if I'm wrong) and I believe they're working on it over at the testfx repo

**Comment by thomhurst** [comment]
Also it might be a limit or the ide. As this is all quite new there's multiple parts here that all need to work together. I think TUnit is fulfilling it's part and that the IDEs simply need to improve support.

**Comment by Xor-el** [comment]
These links below might provide some hints as to what @biqas  is inquiring about.

https://blog.martincostello.com/writing-logs-to-xunit-test-output/

and

https://www.meziantou.net/how-to-view-logs-from-ilogger-in-xunitdotnet.htm

**Comment by thomhurst** [comment]
> These links below might provide some hints as to what @biqas is inquiring about.
> 
> https://blog.martincostello.com/writing-logs-to-xunit-test-output/
> 
> and
> 
> https://www.meziantou.net/how-to-view-logs-from-ilogger-in-xunitdotnet.htm

I'll take a look but this is referring to the old VSTest runner. Tunit runs on the new runner. I don't think you can compare them like for like

**Comment by frankhaugen** [comment]
I really miss `ITestOutputHelper`, or an equivalent. I do lots of weird stuff through tests, like dumping initializer syntax of the data on a failing test, (using my lib of extensions: https://github.com/frankhaugen/Frank.Testing/blob/main/Frank.Testing.TestOutputExtensions/TestOutputCSharpExtensions.cs), so I can re-create the exact state of a flaky test. I just started using TUnit, so I might have alternatives, but I didn't find them immediately.

A similar mechanism, can be an ILogger/ILogger<T> that is exposed in the context that will write to "Test Output" and not just the console, (I use Rider or full Visual Studio)

As a related (vaguely) concept: capturing Console in a test-run is a concept I have toyed with for XUnit, but I might play around in TUnit to see if something fun can be done: https://github.com/captin411/Captin.ConsoleIntercept

**Comment by thomhurst** [comment]
> I really miss `ITestOutputHelper`, or an equivalent. I do lots of weird stuff through tests, like dumping initializer syntax of the data on a failing test, (using my lib of extensions: https://github.com/frankhaugen/Frank.Testing/blob/main/Frank.Testing.TestOutputExtensions/TestOutputCSharpExtensions.cs), so I can re-create the exact state of a flaky test. I just started using TUnit, so I might have alternatives, but I didn't find them immediately.
> 
> A similar mechanism, can be an ILogger/ILogger that is exposed in the context that will write to "Test Output" and not just the console, (I use Rider or full Visual Studio)
> 
> As a related (vaguely) concept: capturing Console in a test-run is a concept I have toyed with for XUnit, but I might play around in TUnit to see if something fun can be done: https://github.com/captin411/Captin.ConsoleIntercept

TUnit captures console output actually. If you check your test context output after a test it should include any console logs.

So by just doing console writeline, your context output will be populated.

If you need to do more with logs, you can create a new class that inherits from TUnitLogger and new that up yourself. Does that help?

**Comment by frankhaugen** [comment]
> > I really miss `ITestOutputHelper`, or an equivalent. I do lots of weird stuff through tests, like dumping initializer syntax of the data on a failing test, (using my lib of extensions: https://github.com/frankhaugen/Frank.Testing/blob/main/Frank.Testing.TestOutputExtensions/TestOutputCSharpExtensions.cs), so I can re-create the exact state of a flaky test. I just started using TUnit, so I might have alternatives, but I didn't find them immediately.
> > A similar mechanism, can be an ILogger/ILogger that is exposed in the context that will write to "Test Output" and not just the console, (I use Rider or full Visual Studio)
> > As a related (vaguely) concept: capturing Console in a test-run is a concept I have toyed with for XUnit, but I might play around in TUnit to see if something fun can be done: https://github.com/captin411/Captin.ConsoleIntercept
> 
> TUnit captures console output actually. If you check your test context output after a test it should include any console logs.
> 
> So by just doing console writeline, your context output will be populated.
> 
> If you need to do more with logs, you can create a new class that inherits from TUnitLogger and new that up yourself. Does that help?

Yeah, stumbled on to it 30 secs after posting, but apparently not deleting quick enough.

Awesome response time!

**Comment by thomhurst** [comment]
As an update for everyone on test IDE output windows.

The test metadata I send behind the scenes to the test framework has only recently included support for test output data.

So this means IDEs haven't developed it yet.

VS should be working on it already.
I don't know if Rider are already or not so I've raised an issue here with them: https://youtrack.jetbrains.com/issue/RIDER-117847/Testing-Platform-Test-Output-not-showing-in-IDE

**Comment by thomhurst** [comment]
Jetbrains have marked the issue as fixed.

Says it'll be available in the Next 2024.3 public build. 🤞

**Comment by thomhurst** [comment]
This is now working in 2024.3 EAP 4. You can either download that, or wait until the official 2024.3 release.

![image](https://github.com/user-attachments/assets/cff3605d-a1b7-4a20-bdd0-465de4a6128c)

**Comment by abhisheksaraiya** [comment]
I suspect that since the `TestContext.Current.OutputWriter` is shared across all the tests that are run, in some cases the logs end up showing in the wrong windows. I mean the logs from some test A bleed into test B sometimes and are missing in test window of test A.
Is someone else also facing such an issue ?

**Comment by FlukeFan** [comment]
Just for anyone else looking at this, `Console.WriteLine(...)` writes to a test-specific log.  To get global logging to the MS testing platform, I used the following hack (I couldn't find a better way of getting acccess to the `TUnitFrameworkLogger`):

```csharp
        var ctx = GlobalContext.Current;
        var get = ctx.GetType().GetProperty("GlobalLogger", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic);
        var logger = (TUnitFrameworkLogger)get!.GetValue(ctx)!;

        logger.LogInformation(message);
```
