### ISSUE TITLE
Instructions on how to use with Visual Studio

### ISSUE THREAD

**Issue by SongPing** [thomhurst/TUnit#563]
Could you please give some detailed instructions on how to use TUnit with Visual Studio?
How to get a simple example work within the Test Explorer?

**Comment by thomhurst** [comment]
Hey @SongPing sorry the docs were unclear - I've just updated them.

You need to install the preview version of visual studio and enable the new testing server mode. Instructions and screenshot is now on the main readme.

**Comment by SongPing** [comment]
Thanks, for your fast reply!
Now it is much clearer, why I didn't get it to work.
I hope, your documentation update will also help others saving time, not trying it with the current Visual Studio Version.
