### ISSUE TITLE
[Nitpick] "popular" type names in "top-level" namespace

### ISSUE THREAD

**Issue by frankhaugen** [thomhurst/TUnit#577]
This is VERY nitpicky and the fix is easy, but I see this getting annoying quite fast:
![image](https://github.com/user-attachments/assets/088f0308-8700-49e3-abca-ed423267b299)

I see there is an "Enums" namspace already, so maybe it belongs there, or a less "every project on earth will have the same type-name"-name:
![image](https://github.com/user-attachments/assets/6e4e2764-efb3-4c4a-a53c-7c13b5870948)

**Comment by thomhurst** [comment]
Fixed in the latest version
