### ISSUE TITLE
BUG: TUnit has trouble with certain nullability in arguments during Source Generation

### ISSUE THREAD

**Issue by HarryCordewener** [thomhurst/TUnit#615]
TUnit will create an 'empty string' during Source Generation instead of null, if it finds Nullability with null values later in Arguments. This causes compile failure.

Reproduced here:
https://github.com/SharpMUSH/SharpMUSH/blob/5179a9c4e80912a03537fe24eb7d9c51dd306651/SharpMUSH.Tests/Functions/StringFunctionUnitTests.cs#L11-L41

Uncomment to see the behavior.

**Comment by thomhurst** [comment]
Thanks @HarryCordewener ! Should be fixed in 0.1.812

**Comment by HarryCordewener** [comment]
I'll test it later tonight and get back to you. But based on the commit, I definitely agree.

**Comment by HarryCordewener** [comment]
Confirmed, the fix works! Thank you very much, Tom!
