### ISSUE TITLE
Some Rider painpoints, and other things

### ISSUE THREAD

**Issue by frankhaugen** [thomhurst/TUnit#620]
Hi, I have spent the weekend rewriting one of my work-projects to use TUnit instead of XUnit, and I have some experiences to share:

My setup:
> JetBrains Rider 2024.2.5
> Build #RD-242.22855.90, built on September 19, 2024
> Runtime version: 21.0.3+13-b509.15 amd64 (JCEF 122.1.9)
> Windows 11.0
> .NET Core v8.0.4 x64 (Server GC)

Experiences:
1. Over-all, I love it, the time to run tests is phenomenal compared to XUnit, the "hook in at any level" is awesome
2. Double-clicking to navigate to test don't work, (right-click-> Jump to source and Show source, also don't work)
3. Messages written to test-output, `TestContext.Current.GetDefaultLogger().LogInformation("LOG ME!");` and `await TestContext.Current.OutputWriter.WriteLineAsync("OUTPUT ME!");`, don't get shown in actual test output after test finishes in Rider. What  is outputted when running CLI. I Use the output of tests a lot
4. `await Assert.That(_this).IsNotNull();` is a little verbose, but `Assert.IsNotNull(_this);`, or `_this.Should().NotBeNull();`, aren't that different
5. I miss fluent assertions, (saw your PR, so just an observation)

Suggestions:
- Wrap Coverage and Reports in TUnit nugets, and leverage nuget to create the config needed with acceptable "defaults" for TUnit. Like you have all the modules for `ModularPipelines`, it would be nice to have defaults for e.g. DevOps

Thank you for making the effort creating this, and I hope you will continue. I'd offer to help, but for the next couple of months, I don't have the bandwidth 😞

**Comment by thomhurst** [comment]
Thanks very much! Appreciate it :)

I believe 2 and 3 are things for Jetbrains to fix.

Go to source works in Visual Studio, so the data is there, I just don't think Rider is using it.

And the test output window I think still hasn't been developed yet, as the testing platform is still very new. They recently added standard output and standard error values, which I have set. I think (but not 100%) that that should drive the test output window in IDEs but the IDE itself will have to look at that value and implement it.

**Comment by SaschaOnTour** [comment]
@frankhaugen your experience sounds great. I'm also thinking about to switch to TUnit. 

If you write an issue for Rider, let it know me here and I will support it. Thanks.

**Comment by thomhurst** [comment]
@frankhaugen @SaschaBa I've raised issues with Jetbrains:

Test output: https://youtrack.jetbrains.com/issue/RIDER-117847/Testing-Platform-Test-Output-not-showing-in-IDE 
Jump to source: https://youtrack.jetbrains.com/issue/RIDER-117848/Testing-Platform-Navigate-to-test-does-not-work

**Comment by SaschaOnTour** [comment]
@thomhurst wow, you are very fast. I voted both issues.

**Comment by thomhurst** [comment]
@frankhaugen out of curiosity what was the difference in speed between xUnit and TUnit for you?

**Comment by thomhurst** [comment]
> @thomhurst wow, you are very fast. I voted both issues.

Looks like they've both been assigned so hopefully we'll see a fix soon!

**Comment by SaschaOnTour** [comment]
:-) yes, and they got both a high priority

**Comment by frankhaugen** [comment]
> @frankhaugen out of curiosity what was the difference in speed between xUnit and TUnit for you?

So I did some really fiddly measuring and I got 13,5 % quicker over 50 runs. I feel it was quicker. I wouldn't count those numbers as "quality assured" but I ran devops pipline on the code before the rewrite and the one after 100 times, (50 of each type).

I feel on my computer its much quicker than 13%

**Comment by thomhurst** [comment]
> @frankhaugen @SaschaBa I've raised issues with Jetbrains:
> 
> Test output: https://youtrack.jetbrains.com/issue/RIDER-117847/Testing-Platform-Test-Output-not-showing-in-IDE Jump to source: https://youtrack.jetbrains.com/issue/RIDER-117848/Testing-Platform-Navigate-to-test-does-not-work

Jetbrains have marked the issue as fixed.

Says it'll be available in the Next 2024.3 public build. 🤞

**Comment by thomhurst** [comment]
It's working now for me in 2024.3 EAP 4. So you can download that if you don't want to wait. Otherwise, it'll just be in the main 2024.3 release.

Because locations are working, you can execute the test using the green play button next to it like xUnit/NUnit now: 

![image](https://github.com/user-attachments/assets/ad82b10c-401a-40df-8e31-58396407ae93)

And the output window is now showing 😄 
![image](https://github.com/user-attachments/assets/b84613a6-d592-4165-b013-abbd45f679f1)

Going to close this for now.

**Comment by sid-6581** [comment]
@thomhurst Does it work for you for parameterized tests as well?

**Comment by thomhurst** [comment]
Just checked, indeed it is only basic tests 😢
