### ISSUE TITLE
What's the point of the `HasCount` assertion?

### ISSUE THREAD

**Issue by c-schembri** [thomhurst/TUnit#645]
https://github.com/thomhurst/TUnit/blob/b484c9d28c423203a26a58bdd8ba41c816b88b23/TUnit.Assertions/Extensions/Has/HasExtensions_Enumerable.cs#L35

What's the point of this assertion? It cannot be awaited and so it effectively cannot be accessed. I would have thought that `HasCount` would be a short-cut of checking some collections `.Count` property against some passed value.

**Comment by thomhurst** [comment]
The idea was this returns an object tbat you can call EqualTo or Greater than etc

**Comment by c-schembri** [comment]
> The idea was this returns an object tbat you can call EqualTo or Greater than etc

Ah of course. Forgive me, I missed that entirely. Thanks for the quick response!
