### ISSUE TITLE
Context.AllTests empty for AfterEvery(TestDiscovery) and BeforeEvery(TestSession) Hooks

### ISSUE THREAD

**Issue by tntwist** [thomhurst/TUnit#668]
Hi there, ✌️

i just found out that there are no tests given in the contexts when hooking into `AfterEvery(TestDiscovery)` and `BeforeEvery(TestSession)`. 

So here a quick example:

Some dummy tests:
```
public class DummyTest
{
    [Test]
    public async Task DummyTestAsync()
    {
        var a = 1;
        var b = 2;
        await Assert.That(a + b).IsEqualTo(3);
    }

    [Test]
    public async Task DummyTest2Async()
    {
        var a = 2;
        var b = 2;
        await Assert.That(a + b).IsEqualTo(4);
    }
}
```

GlobalHooks.cs
```
public static class GlobalHooks
{
    [AfterEvery(TestDiscovery)]
    public static void AfterDiscovery(TestDiscoveryContext context)
    {
        var testCount = context.AllTests.Count();
        // always zero.
        Console.WriteLine($"Test count after discovery: {testCount}");
    }

    [BeforeEvery(TestSession)]
    public static void BeforeSession(TestSessionContext context)
    {
        var testCount = context.AllTests.Count();
        // always zero.
        Console.WriteLine($"Test count before session: {testCount}");
    }

    [Before(Assembly)]
    public static void BootstrapAsync(AssemblyHookContext context)
    {
        var testCount = context.AllTests.Count();
        // 2. But only contains the tests of the specifiy assembly.
        Console.WriteLine($"Test count before assembly: {testCount}");
    }
}
```

I would expect that the TestDiscoveryContext provides all tests that where discovered and the TestSessionContexts provides all tests that are meant to be run in the session regadless of in what assembly they are. It would be really nice to have these informations in these hooks.

I tested this with the latest vs preview version and also just using a plain `dotnet test`. Same result though.

Also one side question:
Why do we have to use `BeforeEvery` and `AfterEvery` for the TestSession and TestDiscovery Hooks? I tested using just `Before` and `After` but both of these did not work and the methods never were called. 

Thanks in advance. :)

**Comment by thomhurst** [comment]
> I would expect that the TestDiscoveryContext provides all tests that where discovered and the TestSessionContexts provides all tests that are meant to be run in the session regadless of in what assembly they are. It would be really nice to have these informations in these hooks.

Yep! That's the intention. This is a bug I must not be populating them.

> Also one side question:
Why do we have to use BeforeEvery and AfterEvery for the TestSession and TestDiscovery Hooks? I tested using just Before and After but both of these did not work and the methods never were called.

This is another bug if this is the case. Before/After Test Discovery/Session should basically behave exactly the same to BeforeEvery/AfterEvery Test Discovery/Session (because there'll only ever be 1 context of each anyway.)
So looks like this is another bug.

Thanks for reporting! I'm out right now but I'll try and get a fix out in the next couple of days 😄

**Comment by tntwist** [comment]
Thanks for the fast reply. 😁

I will grap a beer and try to fix it. 
Will keep you updated ✌️

**Comment by tntwist** [comment]
@thomhurst 
I was able to fix this.

I´ve created to possible fixes for this.

First:
https://github.com/thomhurst/TUnit/compare/main...tntwist:TUnit:fix-session-discovery-hooks?expand=1

Second:
https://github.com/thomhurst/TUnit/compare/main...tntwist:TUnit:fix-session-discovery-hooks-2?expand=1

The first one is just a quick and dirty solution i was not happy with.

The second one is a bit more changes.
In my opinion it makes sense to give the `TestDiscoveryContext` just the discoverted tests since at this stage it does not really make sense to give him the assembly contexts of `AssemblyHookOrchestrator`.

I´ve moved the grouping and registering of the tests out of the TestExecutor and moved it into the TestFramework to have that to be done before the session hook gets called.

Please take a look at both branches and let me know if you happy with one solution.

**Comment by thomhurst** [comment]
Thanks for investigating and creating a fix! @tntwist I think the second solution sounds better like you say. I think I'd still like the session and discovery contests to have assembly properties. This allows us to separate out things, and if someone did want to do certain things per assembly then they could. Would you be able to make that change?

I agree with your comments about the session only containing runnable tests. But I'd still like to group them by assembly, then class, etc.

The all tests property still can stay, but just reference the assembly property and do a linq select many etc. does that make sense?

**Comment by tntwist** [comment]
> I think I'd still like the session and discovery contests to have assembly properties. This allows us to separate out things, and if someone did want to do certain things per assembly then they could. Would you be able to make that change?

Sure think.

> I agree with your comments about the session only containing runnable tests. But I'd still like to group them by assembly, then class, etc.
> 
> The all tests property still can stay, but just reference the assembly property and do a linq select many etc. does that make sense?

Yeah. I left the sorting and grouping stuff as it was and just moved it so the session contexts would get the tests in the right order.

I will move that part now right after the discovery so that the `After(TestDiscovery)` will also have the assembly props and everything else. let me adjust the second one so you can have a look wenn you have time.

**Comment by tntwist** [comment]
ok done. :)

**Comment by thomhurst** [comment]
Cheers, raise a pr and that gives me better visibility and I can easily make any comments.

Thanks again for helping out!
