### ISSUE TITLE
Unable to create custom assertions

### ISSUE THREAD

**Issue by c-schembri** [thomhurst/TUnit#686]
https://github.com/thomhurst/TUnit/blob/3a1580c5e0311b746d8397671255b1359c60d280/TUnit.Assertions/AssertConditions/NullAssertCondition.cs#L10

This method cannot be overriden because it is `private protected` and so only can be overriden in the same assembly (which is impossible for users who include this project as a package).

**Comment by thomhurst** [comment]
Thanks @c-schembri . Can you try version 0.1.885?

**Comment by c-schembri** [comment]
> Thanks @c-schembri . Can you try version 0.1.885?

It's working now in 0.1.885. Thanks for the fix.
