### ISSUE TITLE
Provide more complex samples using `WebApplicationFactory`

### ISSUE THREAD

**Issue by rigtigeEmil** [thomhurst/TUnit#708]
Heya. The library looks super promising, but it can be hard to compare what a potential implementation might look like when using more "complex" setups that require testing against a `WebApplicationFactory`.

My current setup uses [Test containers](https://dotnet.testcontainers.org/) to spin up a Postgres database, once before running these integration tests. This requires an async function to execute `await PostgresSqlContainer.StartAsync();`. Currently this is "fine", and is solved using `IAsyncLifetime`. Once completed, this can be used in the overriden function `ConfigureWebHost` of the `WebApplicationFactory`. I'm unsure how the same can be achieved with TUnit.

As I'm sure you know, this means spinning up the database, setting up schemas etc. once before all tests run fairly easy - once you grasp the lifecycles of XUnit. 

With my current test setup, this means all tests get this `WebApplcationFactory` injected into them, so they have the `CreateClient` available to them. I'm also unsure how this (or a simpler approach) is achieved with TUnit.

Thanks a bunch!

**Comment by thomhurst** [comment]
Hey @rigtigeEmil  -  Does this help? https://thomhurst.github.io/TUnit/docs/tutorial-basics/class-data-source

You can inject things similarly to how xUnit does.

Or you could do basic Before/After(TestSession) hooks and create/dispose a static WebApplicationFactory: https://thomhurst.github.io/TUnit/docs/tutorial-extras/setup

**Comment by rigtigeEmil** [comment]
@thomhurst Yes and no - I've looked through these docs, and they don't quite satisfy what I'm looking for.

It could be my knowledge of the `WebApplicationFactory` coming up short, but I've only ever had it injected and "just work" through ctor injection. Typically this has meant to ask for it in any test class, and pass it down to a base class, that would do whatever database-initialization necessary before providing a HttpClient for testing. 

I'd be super nice to be able to define a base class that, using `Before(TestSession/Assembly)` be able to initialize protected properties, but also having the ability to re-configure test services in the factory, without having to drill the factory itself from each test class as a dependency.

**Comment by thomhurst** [comment]
@rigtigeEmil would you be able to post xUnit code that does all this? It'll help me understand better and try to help you get a like for like solution.

**Comment by rigtigeEmil** [comment]
@thomhurst good idea, that probably makes it a bit easier. There's also some .. questionable code here, so if it's just because of me misusing some other stuff, please bear with me. Hopefully this some idea of what I'm trying to accomplish.

https://gist.github.com/rigtigeEmil/03c979f306d646a66580623803f57e17

**Comment by thomhurst** [comment]
@rigtigeEmil Does this not work? It's fairly similar to xUnit but without the need of the CollectionFixtureDefinition:

```csharp
public class GilbertWebApplicationFactory
    : WebApplicationFactory<Gilbert.API.Program>,
        IAsyncInitializer, IAsyncDisposable
{
    public PostgreSqlContainer PostgresSqlContainer { get; } = new PostgreSqlBuilder().Build();

    public HttpClient CreateGilbertClient(
        Merchant? merchant
        // ..
    )
    {
        var client = base.CreateClient();
        if (merchant is not null)
            client.DefaultRequestHeaders.Add("Merchant-Id", merchant.Id.Value);

        // ..
        return client;
    }

    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        base.ConfigureWebHost(builder);
        builder.ConfigureTestServices(services =>
        {
            // ...
        });
    }

    public async Task InitializeAsync()
    {
        OaktonEnvironment.AutoStartHost = true;
        await PostgresSqlContainer.StartAsync();
    }

    public async ValueTask DisposeAsync()
    {
        await base.DisposeAsync();
        await PostgresSqlContainer.DisposeAsync();
    }
}

[ClassDataSource<GilbertWebApplicationFactoryFixture>(Shared = SharedType.Keyed, Key = "GilbertWebApplicationFactoryFixture")]
public abstract class GilbertApiTestBase(GilbertWebApplicationFactory factory)
{
    protected Merchant Merchant { get; set; } = null!;
    private IDocumentStore DocumentStore => factory.Services.GetRequiredService<IDocumentStore>();
    protected IDocumentSession GlobalDocumentSession { get; private set; } = null!; 

    // ...
    
    [Before(Test)]
    public async Task InitializeAsync()
    {
        GlobalDocumentSession = factory
            .Services.GetRequiredService<IDocumentStore>()
            .LightweightSession();
        await InitializeMerchant();
    }

    protected HttpClient CreateClient() =>
        factory.CreateGilbertClient(
            Merchant
            // ..
        );

    
    protected async Task<Domain.Features.Customer.Customer> CreateCustomer() { }

    // .. bunch of helper methods for setup
    
    private async Task InitializeMerchant()
    {
        var merchant = new Merchant()
        GlobalDocumentSession.StartStreamGlobal(merchant);
    }
}

public class Create(GilbertWebApplicationFactory factory) : GilbertApiTestBase(factory)
{
    [Test]
    public async Task CustomerCreate_ReturnsCreated()
    {
        // Arrange
        var client = base.CreateClient();

        // Act
        // Assert
    }
}
```

**Comment by rigtigeEmil** [comment]
That does look like what I was missing, although I had wished for a prettier solution. 
With this, it seems like it's necessary to decorate all test classes with `ClassDataSource`. Is there any way to mark an property as being an injected one, without involving the ctor? For example, something like this, to avoid having to drill the class to the base constructor in all inheritors:
```cs
public class GilbertBffApiTestBase()
{
    [ClassDataSource<GilbertWebApplicationFactoryFixture>(Shared = SharedType.Keyed, Key = "GilbertWebApplicationFactoryFixture")]
    private GilbertWebApplicationFactoryFixture Fixture { get; }
}
```

**Comment by thomhurst** [comment]
> With this, it seems like it's necessary to decorate all test classes with ClassDataSource

In the latest version, only the base needs it. But you'll still need each inherited class to provide the ctor.

I haven't built any property injection currently. I'm unsure of whether I want to because ctor injection is just cleaner imo.

But I'll have a think.

**Comment by thomhurst** [comment]
Actually a good compromise could be required properties set using an object initialiser. Will probably take me to some to implement though.

**Comment by rigtigeEmil** [comment]
I think this is a nitpick, but it would make tests quicker and easier to write - just inherit from this class, and you're off to the races. Thanks for the responses, I'll give the library a go and get back if I have other questions

**Comment by thomhurst** [comment]
@rigtigeEmil I've implemented property injection in the latest version! The docs are here: https://thomhurst.github.io/TUnit/docs/tutorial-extras/property-injection

I haven't written any analyzers yet so you don't get warnings if you use wrong types etc. But I will add those soon.

But you should still be able to test it out.

**Comment by rigtigeEmil** [comment]
@thomhurst Wow, that was quick. Nice, I'll take a look and try it out later today. Thanks!

**Comment by rigtigeEmil** [comment]
@thomhurst docs seem a bit outdated here: https://thomhurst.github.io/TUnit/docs/tutorial-extras/setup

Is `[Before(EachTest)]` equivalent to `[BeforeEvery(Test)]`. Doesn't seem that way, since an analyzer is complaining about the method not being static (I don't want it to be static, I want it to initialize stuff for each test).
`TUnit0007: Method must be static`
```cs
[BeforeEvery(Test)]
public async Task SetupMerchant()
{
    // setup merchant
}
```

**Comment by thomhurst** [comment]
@rigtigeEmil `[Before(Test)]` will run before each test in the class it's defined in.

`[BeforeEvery(Test)]` is a global hook that runs on every test in the test session, hence being static, because it doesn't relate to one class.

You just want `[Before(Test)]` here

**Comment by rigtigeEmil** [comment]
Ah, nice! Cheers

**Comment by rigtigeEmil** [comment]
@thomhurst  I'm unsure if I'm doing something wrong. Example is mostly similar to before, but some things I didn't expect are happening:
1. `ConfigureWebHost` is being invoked before `InitializeAsync` in the following code, and `ConfigureWebHost` is being invoked twice (I have two tests):
```cs
public class GilbertWebApplicationFactory
    : WebApplicationFactory<Gilbert.API.Program>,
        IAsyncInitializer,
        IAsyncDisposable
{
    public PostgreSqlContainer PostgresSqlContainer { get; } = new PostgreSqlBuilder().Build();

    public async Task InitializeAsync()
    {
        OaktonEnvironment.AutoStartHost = true;
        await PostgresSqlContainer.StartAsync();
    }

    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.ConfigureTestServices(services =>
        {
            // ..
        });
        base.ConfigureWebHost(builder);
    }

    public new async ValueTask DisposeAsync()
    {
        await base.DisposeAsync();
        await PostgresSqlContainer.DisposeAsync();
    }
}
```
2. `SetupMerchant` in my base class that should have the factory injected is invoked before anything in the factory. Once the first usage of the factory is hit, it jumps to the `ConfigureWebHost` above - but never the initialize function in the factory itself
```cs
public abstract class GilbertBffApiTestBase
{
    [ClassDataSource<GilbertWebApplicationFactory>(Shared = SharedType.Globally)]
    public required GilbertWebApplicationFactory Factory { get; init; }
    protected IDocumentSession GlobalDocumentSession { get; private set; } = null!;

    [Before(Test)]
    public async Task SetupMerchant()
    {
        GlobalDocumentSession = Factory
            .Services.GetRequiredService<IDocumentStore>()
            .LightweightSession(); // throws here

        // ..
    }
}
```
3. My tests look like this (they're never hit, since the exception is thrown on exiting `ConfigureWebhost`
```cs
public class Create : GilbertBffApiTestBase
{
    [Test]
    public async Task A()
    {
        var expected = 1;
        var actual = 1;
        await Assert.That(actual).IsEqualTo(expected);
    }

    [Test]
    public async Task B()
    {
        var expected = 1;
        var actual = 1;
        await Assert.That(actual).IsEqualTo(expected);
    }
}
```

```
Error executing Before(Test) method: GilbertBffApiTestBase.SetupMerchant()
   at TUnit.Core.TestRegistrar.<>c__DisplayClass5_0`1.<<RegisterBeforeHook>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at TUnit.Engine.Helpers.Timings.Record(String name, TestContext context, Func`1 action)
   at TUnit.Engine.Hooks.TestHookOrchestrator.ExecuteBeforeHooks(Object classInstance, DiscoveredTest discoveredTest)
   at TUnit.Engine.Services.TestInvoker.Invoke(DiscoveredTest discoveredTest, CancellationToken cancellationToken)
   at TUnit.Engine.Services.SingleTestExecutor.ExecuteTestMethodWithTimeout(DiscoveredTest discoveredTest)
   at TUnit.Engine.Services.SingleTestExecutor.ExecuteCore(DiscoveredTest discoveredTest)
   at TUnit.Engine.Services.SingleTestExecutor.ExecuteWithRetries(DiscoveredTest discoveredTest)
   at TUnit.Engine.Services.SingleTestExecutor.ExecuteWithRetries(DiscoveredTest discoveredTest)
   at TUnit.Engine.Services.SingleTestExecutor.ExecuteTestInternalAsync(DiscoveredTest test, ITestExecutionFilter filter, ExecuteRequestContext context, Boolean isStartedAsDependencyForAnotherTest)
   at TUnit.Engine.Services.SingleTestExecutor.ExecuteTestInternalAsync(DiscoveredTest test, ITestExecutionFilter filter, ExecuteRequestContext context, Boolean isStartedAsDependencyForAnotherTest)
```

**Comment by thomhurst** [comment]
@rigtigeEmil  I think that might've been related to the new property injection. I hadn't set up the initialisation logic properly.

I've just pushed out a new version -  0.1.928

Can you see if that sorts it? If not I'll keep investigating

**Comment by rigtigeEmil** [comment]
@thomhurst I think nuget is still churning, I only see .923 - I'll try it and get back when its ready

**Comment by rigtigeEmil** [comment]
@thomhurst Works like a charm. So nice!! Thanks for the quick fix, much appreciated

**Comment by thomhurst** [comment]
Amazing! ❤️

**Comment by rigtigeEmil** [comment]
@thomhurst back again 😁
Is there any reason why injected properties can't be static (and, really minor, why the property can't be protected)? 
I want to run some global setup to initialize some shared variables like so:
```cs
public abstract class GilbertBffApiTestBase
{
    [ClassDataSource<GilbertWebApplicationFactory>(Shared = SharedType.Globally)]
    public required GilbertWebApplicationFactory Factory { get; init; }
    protected static IDocumentSession GlobalDocumentSession { get; private set; } = null!;
    [Before(TestSession)]
    public static async Task PrepareDatabase()
    {
        GlobalDocumentSession = Factory  // 💢 Factory must be static
            .Services.GetRequiredService<IDocumentStore>()
            .LightweightSession();
            
            // poke database, set schema, shared data, whatever
    }
}
```

edit* 

Right .. because it's required. I understand your reasoning for it, but I think there's two core principles clashing then - `[Before(TestSession)` must be static, but globally injected properties can't be? Maybe I'm just missing something obvious

**Comment by thomhurst** [comment]
I think the confusion is just because you're defining a Before(TestSession) within your class.

Because they affect the entire session, it makes more sense to split them out into their own class. It's on my to-do list to write an analyzer enforce global hooks being in their own class so set ups are easier to find.

Also injected properties can have different lifetimes. But static lives on forever beyond class instances. It'd just be messy I think.

And regarding abstract, what would that look like/how are you trying to use it?

Does that make sense?

**Comment by rigtigeEmil** [comment]
Stripped of the boring stuff, this is the relevant code. The factory is injected into a base class. I'd like that base class to initialize some stuff that will be used for almost all integration tests. In this case, once the database has been prepared, I want to initialize a property that'll be used in many tests (`GlobalDocumentSession`) along with some others. 

It also initializes some stuff for each test (this part seems to work like I expect).

```cs

public class GilbertWebApplicationFactory
    : WebApplicationFactory<Gilbert.API.Program>,
        IAsyncInitializer,
        IAsyncDisposable
{
    public PostgreSqlContainer PostgresSqlContainer { get; } = new PostgreSqlBuilder().Build();

    public async Task InitializeAsync()
    {
        OaktonEnvironment.AutoStartHost = true;
        await PostgresSqlContainer.StartAsync();
    }

    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.ConfigureTestServices(services =>
        {
            // ..
        });
        base.ConfigureWebHost(builder);
    }

    public new async ValueTask DisposeAsync()
    {
        await base.DisposeAsync();
        await PostgresSqlContainer.DisposeAsync();
    }
}
```

```cs
public abstract class GilbertBffApiTestBase
{
    [ClassDataSource<GilbertWebApplicationFactory>(Shared = SharedType.Globally)]
    public required GilbertWebApplicationFactory Factory { get; init; }

    protected static IDocumentSession GlobalDocumentSession { get; private set; } = null!;
    protected HttpClient Client { get; private set; } = null!;
    protected Merchant Merchant { get; private set; } = null!;
    protected User User { get; private set; } = null!;
    
    [Before(TestSession)]
    public static async Task PrepareDatabase()
    {
        GlobalDocumentSession = Factory 
            .Services.GetRequiredService<IDocumentStore>()
            .LightweightSession();
    }

    [Before(Test)]
    public async Task PrepareTest()
    {
        GlobalDocumentSession = Factory
            .Services.GetRequiredService<IDocumentStore>()
            .LightweightSession();

        var user = await CreateUser();
        var merchant = await CreateMerchant(User);

        Client = Factory.CreateClient();
        Client.DefaultRequestHeaders.Add("Merchant-Id", merchant.Id.Value);
        Client.DefaultRequestHeaders.Add("User-Id", user.Id.Value);
        Client.DefaultRequestHeaders.Add("User-Email", user.Email.Value);
    }
}
```

And finally, tests will, in many cases just look like this:
```cs
public class Create : GilbertBffApiTestBase
{
    [Test]
    public async Task MyTest()
    {
        // Arrange
        // Act

        var response = await Client.PostAsJsonAsync("/api/customers", GetSomeRequest());

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.Forbidden);
    }
}
```

**Comment by thomhurst** [comment]
So from what I can tell, it'd be useful to:

Have a test session set up class, where you could inject in that instance, and perform a one time setup?

**Comment by rigtigeEmil** [comment]
I'm not sure I understand what the difference would be. You'd suggest to wrap my `PrepareDatabase` function into a class, and inject that class into `GilbertBffApiTestBase`?

Personally I prefer to be able to scan a single file and get an overview of the setup happening - ie. see all my `[Before(TestSession)]`, `[Before(Test)]` and whatnot functions, and what they're doing

**Comment by thomhurst** [comment]
```
[Before(TestSession)]
    public static async Task PrepareDatabase()
    {
        GlobalDocumentSession = Factory 
            .Services.GetRequiredService<IDocumentStore>()
            .LightweightSession();
    }
```

Can you not do this within the InitializeAsync of the Factory class? Since you're sharing it globally, it'll only be new'd up once. So initialising it there would be similar to the Before(TestSession). 

Then it's already initialised for any class you inject it into.

**Comment by rigtigeEmil** [comment]
I don't think that works. The factory isn't properly available until after `ConfigureWebHost` has run. `InitializeAsync` runs before `ConfigureWebHost`. Either way, I still think there's something missing here. It seems like there's two major rules in play
1. Methods that setup each individual test (`[Before(Test)]`) must be non-static
2. Methods that setup any shared state must be static 

But this breaks a little when injected (shared state) properties are forced to be non-static. While I might be able to solve this problem right now with some workaround, I don't think the design quite works.

It also forces me to put various helper functions into the factory, where I might not want it. In this case for example, the factory might be re-used in different base-classes, without needing to share the same initialization. I can't do that without building factories for each use case, or with some other hacky workaround.

Put another way; if the injected property could be static, I'm fairly sure it'd solve the above problems, and also align with the design principles. It could be dependent on the `SharedType` provided to the `ClassDataSource`, but when `SharedType.Globally` is used, I think the above is quite fitting

**Comment by thomhurst** [comment]
@rigtigeEmil Try 0.1.937 - You should be able to register it statically now as its global. Does it solve your problem?

**Comment by rigtigeEmil** [comment]
It throws a nullref, but compilation wise, yes! It seems to solve exactly what I was after:
```
 Gilbert.Tests.API.BFF test failed with 2 error(s) (0,4s)
    C:\git\Gilbert\tests\Gilbert.Tests.API.BFF\GilbertBffApiTestBase.cs(43): error test failed:
      Before Assembly: GilbertBffApiTestBase.PrepareAssembly() (5ms): Object reference not set to an instance of an object.
      Stack Trace:
         at Gilbert.Tests.API.BFF.GilbertBffApiTestBase.PrepareAssembly() in C:\git\Gilbert\tests\Gilbert.Tests.API.BFF\GilbertBffApiTestBase.cs:line 43
         at TUnit.Core.AsyncConvert.Convert(Func`1 action)
         at TUnit.Core.RunHelpers.<>c__DisplayClass0_0.<<RunWithTimeoutAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at TUnit.Core.RunHelpers.RunWithTimeoutAsync(Func`2 taskDelegate, Nullable`1 timeout)
         at TUnit.Core.RunHelpers.RunWithTimeoutAsync(Func`2 taskDelegate, Nullable`1 timeout)
         at TUnit.Engine.Services.HookMessagePublisher.Push(String sessionId, String displayName, StaticHookMethod hookMethod, Func`1 func)
         at TUnit.Engine.Services.HookMessagePublisher.Push(String sessionId, String displayName, StaticHookMethod hookMethod, Func`1 func)
         at TUnit.Core.TestRegistrar.<>c__DisplayClass9_0.<<RegisterBeforeHook>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at TUnit.Engine.Hooks.AssemblyHookOrchestrator.ExecuteBeforeHooks(ExecuteRequestContext executeRequestContext, Assembly assembly, TestContext testContext)
         at TUnit.Engine.Services.SingleTestExecutor.ExecuteBeforeHooks(DiscoveredTest test, ExecuteRequestContext context, TestContext testContext)
```

```cs
    [Before(Assembly)]
    public static async Task PrepareAssembly()
    {
        GlobalDocumentSession = Factory
            .Services.GetRequiredService<IDocumentStore>()
            .LightweightSession();
        // await CreateCountryVat();
    }
```

**Comment by rigtigeEmil** [comment]
Ah, it seems to invoke the `PrepareAssembly` function before the static `GilbertWebApplicationFactory` has been initialized

**Comment by thomhurst** [comment]
@rigtigeEmil I've just pushed out 0.1.939

I've added tests to assert the order so hopefully it'll all work now!

Output from a test:
```
Initializing Static Property
Before Test Session
Before Assembly
Before Class
Initializing Property
Initializing Property
Initializing Property
Initializing Property
Running Test
StaticInnerModel { IsInitialized = True, Foo = Bar }
Disposing Property
Disposing Static Property
```

**Comment by rigtigeEmil** [comment]
@thomhurst it seems the issue with `ConfigureWebHost` being called before `InitializeAsync` has returned. But the property is indeed being constructed before the test session function 👍

**Comment by thomhurst** [comment]
> @thomhurst it seems the issue with `ConfigureWebHost` being called before `InitializeAsync` has returned. But the property is indeed being constructed before the test session function 👍

Hmm... This is very confusing.

Would you be able to give me some reproduction code please?

Doesn't have to be exactly your code ATM if that's sensitive. Just a minimal reproduction will do.

**Comment by rigtigeEmil** [comment]
Yeah, this should replicate it, you just need to have a `Program` entrypoint to feed the factory. I have three files, `MyFactory`, `MyTestBase` and `MyTests`. I'm debugging them using Rider:
```
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentAssertions" Version="7.0.0-alpha.3" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.8" />
        <PackageReference Include="Testcontainers.PostgreSql" Version="3.10.0" />
        <PackageReference Include="TUnit" Version="0.1.939" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Gilbert.API.BFF\Gilbert.API.BFF.csproj" />
    </ItemGroup>
</Project>
```
```cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.AspNetCore.TestHost;
using Testcontainers.PostgreSql;
using TUnit.Core.Interfaces;

namespace ConsoleApp1;

public class MyFactory
    : WebApplicationFactory<Gilbert.API.Program>,
        IAsyncInitializer,
        IAsyncDisposable
{
    public PostgreSqlContainer PostgresSqlContainer { get; } = new PostgreSqlBuilder().Build();

    public async Task InitializeAsync()
    {
        // stick a breakpoint here - will be hit 2nd
        await PostgresSqlContainer.StartAsync();
    }

    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.ConfigureTestServices(services => { });
        // stick a breakpoint here - will be hit 1st
        base.ConfigureWebHost(builder);
    }

    public new async ValueTask DisposeAsync()
    {
        await base.DisposeAsync();
        await PostgresSqlContainer.DisposeAsync();
    }
}
```
```cs
namespace ConsoleApp1;

public abstract class MyTestBase
{
    [ClassDataSource<MyFactory>(Shared = SharedType.Globally)]
    public static MyFactory Factory { get; set; } = null!;

    [Before(TestSession)]
    public static async Task PrepareSession()
    {
        Factory.CreateClient();
        // this doesn't happen because the client breaks,
        // imagine some async initialization here
        var somethingAfterCreateClient = 1;
    }
}
```
```cs
using FluentAssertions;

namespace ConsoleApp1;

public class MyTests : MyTestBase
{
    [Test]
    public void Test1()
    {
        var expected = 1;
        var actual = 1;
        expected.Should().Be(actual);
    }

    [Test]
    public void Test2()
    {
        var expected = 1;
        var actual = 1;
        expected.Should().Be(actual);
    }
}
```

**Comment by thomhurst** [comment]
What does your `Program` contain?

**Comment by rigtigeEmil** [comment]
Eh, quite a bit of configuration. Could that make a difference? Let me try with an empty api template, one sec

**Comment by rigtigeEmil** [comment]
Issue is the same with a new template api. Complete `Program` file here:
```cs
var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

var summaries = new[]
{
    "Freezing",
    "Bracing",
    "Chilly",
    "Cool",
    "Mild",
    "Warm",
    "Balmy",
    "Hot",
    "Sweltering",
    "Scorching"
};

app.MapGet(
        "/weatherforecast",
        () =>
        {
            var forecast = Enumerable
                .Range(1, 5)
                .Select(index => new WeatherForecast(
                    DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
                    Random.Shared.Next(-20, 55),
                    summaries[Random.Shared.Next(summaries.Length)]
                ))
                .ToArray();
            return forecast;
        }
    )
    .WithName("GetWeatherForecast")
    .WithOpenApi();

app.Run();

record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}

namespace Webapplication1
{
    public class Program;
}
```

Meaning the factory becomes:
```cs
public class MyFactory
    : WebApplicationFactory<Webapplication1.Program>,
        IAsyncInitializer,
        IAsyncDisposable
{
    public PostgreSqlContainer PostgresSqlContainer { get; } = new PostgreSqlBuilder().Build();

    public async Task InitializeAsync()
    {
        // stick a breakpoint here - will be hit 2nd
        await PostgresSqlContainer.StartAsync();
    }

    protected override void ConfigureWebHost(IWebHostBuilder builder)
    {
        builder.ConfigureTestServices(services => { });
        // stick a breakpoint here - will be hit 1st
        base.ConfigureWebHost(builder);
    }

    public new async ValueTask DisposeAsync()
    {
        await base.DisposeAsync();
        await PostgresSqlContainer.DisposeAsync();
    }
}
```

**Comment by thomhurst** [comment]
Thanks @rigtigeEmil ! I think it was an issue with my source generator not looking at base classes!

So could you try 0.1.942? I've just pushed it so should be out in the next 5-10 minutes.

Fingers crossed 🫰

**Comment by rigtigeEmil** [comment]
Nice! The initialization runs in the expected sequence now! My initialization logic for the database stuff directly is also working!🥂 

Only issue now is that invoking the api through the factory doesn't work 😄 
I'm seeing what seems to be an exception tied to swagger? But the issue seems that it can't load some DLL. My old test project using XUnit is working with this same api.
```
 Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
      Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
      Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
      Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
      Could not load file or assembly 'Microsoft.Build.Utilities.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
         at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
         at System.Reflection.RuntimeModule.GetTypes()
         at MicroElements.Swashbuckle.FluentValidation.AspNetCore.ReflectionDependencyInjectionExtensions.<>c.<GetByFullName>b__0_1(Assembly assembly) in /home/runner/work/MicroElements.Swashbuckle.FluentValidation/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/AspNetCore/ReflectionDependencyInjectionExtensions.cs:line 24
```

**Comment by thomhurst** [comment]
Hahaha we're slowly getting there!! I'm off out now but will take a look tomorrow if I can. Does your other repro reproduce it? If not, chuck me one please. Sorry for the back and forth, really appreciate the cooperation!

**Comment by thomhurst** [comment]
Hahaha we're slowly getting there!! I'm off out now but will take a look tomorrow if I can. Does your other repro reproduce it? If not, chuck me one please. Sorry for the back and forth, really appreciate the cooperation!

**Comment by rigtigeEmil** [comment]
No worries, I'm just excited to get this working now. The stuff that _does_ work is just much cleaner to my eye, and if the parallelization works nicely as well, it'll be super cool. My first example doesn't have the same issue, but adding fluent validation to it triggers the issue. So adding these lines causes it. I suspect this is just the tip of the iceberg, and that other required dll's will fail when this is fixed
```cs
services.AddValidatorsFromAssemblyContaining<Program>();
services.AddFluentValidationRulesToSwagger();
```

So the test setup is the same as below, but with these packages, and the two new services registered:
```
    <ItemGroup>
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.10.0" />
        <PackageReference Include="MicroElements.Swashbuckle.FluentValidation" Version="6.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.8"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0"/>
    </ItemGroup>
```
```cs
// Add services to the container.
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
var services = builder.Services;
services.AddEndpointsApiExplorer();
services.AddSwaggerGen();
services.AddValidatorsFromAssemblyContaining<Program>();
services.AddFluentValidationRulesToSwagger();

var app = builder.Build();
```



> Issue is the same with a new template api. Complete `Program` file here:
> 
> ```cs
> var builder = WebApplication.CreateBuilder(args);
> 
> // Add services to the container.
> // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
> builder.Services.AddEndpointsApiExplorer();
> builder.Services.AddSwaggerGen();
> 
> var app = builder.Build();
> 
> // Configure the HTTP request pipeline.
> if (app.Environment.IsDevelopment())
> {
>     app.UseSwagger();
>     app.UseSwaggerUI();
> }
> 
> app.UseHttpsRedirection();
> 
> var summaries = new[]
> {
>     "Freezing",
>     "Bracing",
>     "Chilly",
>     "Cool",
>     "Mild",
>     "Warm",
>     "Balmy",
>     "Hot",
>     "Sweltering",
>     "Scorching"
> };
> 
> app.MapGet(
>         "/weatherforecast",
>         () =>
>         {
>             var forecast = Enumerable
>                 .Range(1, 5)
>                 .Select(index => new WeatherForecast(
>                     DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
>                     Random.Shared.Next(-20, 55),
>                     summaries[Random.Shared.Next(summaries.Length)]
>                 ))
>                 .ToArray();
>             return forecast;
>         }
>     )
>     .WithName("GetWeatherForecast")
>     .WithOpenApi();
> 
> app.Run();
> 
> record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
> {
>     public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
> }
> 
> namespace Webapplication1
> {
>     public class Program;
> }
> ```
> 
> Meaning the factory becomes:
> 
> ```cs
> public class MyFactory
>     : WebApplicationFactory<Webapplication1.Program>,
>         IAsyncInitializer,
>         IAsyncDisposable
> {
>     public PostgreSqlContainer PostgresSqlContainer { get; } = new PostgreSqlBuilder().Build();
> 
>     public async Task InitializeAsync()
>     {
>         // stick a breakpoint here - will be hit 2nd
>         await PostgresSqlContainer.StartAsync();
>     }
> 
>     protected override void ConfigureWebHost(IWebHostBuilder builder)
>     {
>         builder.ConfigureTestServices(services => { });
>         // stick a breakpoint here - will be hit 1st
>         base.ConfigureWebHost(builder);
>     }
> 
>     public new async ValueTask DisposeAsync()
>     {
>         await base.DisposeAsync();
>         await PostgresSqlContainer.DisposeAsync();
>     }
> }
> ```

**Comment by thomhurst** [comment]
`services.AddFluentValidationRulesToSwagger()`

Guessing this is the current offender!

Thanks for the info. Will try to investigate in the next couple of days

**Comment by rigtigeEmil** [comment]
Thanks! I've added a PR with the repro projects
https://github.com/thomhurst/TUnit/pull/760

**Comment by thomhurst** [comment]
@rigtigeEmil I was able to replicate but not convinced it's anything to do with TUnit.

The stacktrace is coming from `MicroElements.OpenApi.FluentValidation`

I managed to fix it by installing the NuGet package `Microsoft.Build.Utilities.Core 17.11.4` into the Web project.

Maybe that package needs to transitively pull it in?

**Comment by thomhurst** [comment]
I've found the culprit code in that library actually and found a fix. If it gets merged you shouldn't need to install that separate package. But for now it's a workaround at least: https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/pull/148

Although the repository doesn't look particularly active. Fingers crossed though.

**Comment by rigtigeEmil** [comment]
@thomhurst I've never had this package installed directly, so it's odd that there's a difference between test frameworks. Testing works when using XUnit. I wonder if they're doing some magic to get it working?

**Comment by thomhurst** [comment]
@rigtigeEmil TUnit is built on top of the newer Microsoft.Testing.Platform, and that is a complete rewrite of the .NET testing tools. Previously all testing was via the VSTest host. I'm going to assume that the VSTest host probably loaded that Microsoft.Build package (because it has logic for loading/parsing/building c# projects) and thus it was in the app domain. Since Microsoft.Testing.Platform is a new library with basically no dependencies, nothing gets loaded really apart from what TUnit brings in, and of course your own code. And neither of us needed that assembly so it didn't get loaded. That's my best guess (and could be wrong!).

**Comment by rigtigeEmil** [comment]
@thomhurst Makes good sense actually. It does indeed work if I just include the package directly, and it seems there are no stoppers with TUnit for me at this point, so thanks a bunch for the help! 🫶

**Comment by thomhurst** [comment]
Brilliant 😄 I'm gonna close this now. If you stumble across anything else feel free to raise more issues. Fingers crossed it all goes well from here on haha
