### ISSUE TITLE
MaximumParallelTests might get exceeded when using `NotInParallelAttribute([keys])` and normal tests

### ISSUE THREAD

**Issue by campersau** [thomhurst/TUnit#735]
Since both of these groups are running concurrently does it mean that the real concurrent test count is actually `_maximumParallelTests * 2` when using `NotInParallelAttribute([keys])` and "normal" tests together?

https://github.com/thomhurst/TUnit/blob/ba9dc4901873ac0919244541794a65aaf73eaee4/TUnit.Engine/Services/TestsExecutor.cs#L40-L44

Reference: https://github.com/thomhurst/TUnit/pull/733#issue-2565861185

**Comment by thomhurst** [comment]
Should be resolved in 0.1.923
