### ISSUE TITLE
Add reason for test failure

### ISSUE THREAD

**Issue by vbreuss** [thomhurst/TUnit#747]
I really like your project and would be happy to contribute.
After having a look, I couldn't find anything for specifying the reason for a test failure. `FluentAssertions` uses a because parameter and I would suggest a similar approach:
```csharp
public class InvokableValueAssertionBuilder<TActual>
{
    public InvokableValueAssertionBuilder<TActual> Because(string because, params object[] becauseArgs)
    {
        // This will set a "Because" property in the `BaseAssertCondition` that can be included in the failure message
        this.Assertions.Peek().SetBecauseReason(because, becauseArgs);
        return this;
    }
}
```

Usage would be e.g.
```csharp
    [Test]
    public async Task Contains_With_Because()
    {
        var str = "some long string";

        await Assert.That(str).Contains("bar").Because("it should");
    }
```

What are your thoughts on this?
Are you open for contributions at this stage?

**Comment by thomhurst** [comment]
I would like to include a reason yes 😄 

I'd like to consider chaining in this too.

- Would we provide 1 reason for the whole chain?
- Would we provide reasons per individual assertion in the chain? Does that then become less readable? I suppose it could be put on multiple lines to make clearer

```csharp
        await Assert.That(str)
           .Contains("foo").Because("this field is populated");
           .And.Contains("bar").Because("that field is populated");
```

Do you think that's clear or messy?

**Comment by vbreuss** [comment]
I think a pragmatic approach would be to apply the because on all assertions before it, so if I only include it once at the end, it will always be visible, but I could add multiple different reasons in between.

If it is okay with you, I will create a PR for this feature and we can discuss details there.

**Comment by thomhurst** [comment]
Sure if you'd like to take this on, go for it, and we'll see how the API looks afterwards 😄
