### ISSUE TITLE
Add assertions for floating numbers with tolerance

### ISSUE THREAD

**Issue by vbreuss** [thomhurst/TUnit#765]
It would be a good addition to the assertion library to allow floating point numbers to be compared with a given tolerance, so e.g.
```csharp
double sut = 0.9999997;
Assert.That(sut).IsApproximately(1.0, 0.00001);
```
or 
```csharp
double sut = 0.9999997;
Assert.That(sut).IsEqualTo(1.0).Within(0.00001);
```

**Comment by thomhurst** [comment]
@vbreuss This (and your changes) should be in v0.1.949. Just pushing to nuget now.
