### ISSUE TITLE
Test explorer groups test wrong

### ISSUE THREAD

**Issue by rigtigeEmil** [thomhurst/TUnit#796]
I'm unsure if this is TUnit or some missing implementation on Rider's side (or M$ if it's in the core library), but the test explorer is not grouping tests correctly by their file.
I have a test structure like this, where the top level is a directory, and the directory contains a test file for each action (in this case  CRUD):
- ApiKey
    - Create
    - Get
    - ...
- Customer
    - Create
    - Get
    - ...
- Merchant
    - Create
    - Get
    - ...

 This is not mirrored in the test explorer, where it seems the tests are grouped by the file name, and not necessarily from the directory the files are in. In this case, I'd expect a top-level directory in the test explorer for each entity type, each with levels below it for each class inside the directory
![image](https://github.com/user-attachments/assets/3347da84-d146-4860-88fa-ced8c0f411a0)

**Comment by thomhurst** [comment]
Unfortunately test frameworks don't (yet) have much control over the layout of this. 

There's an issue here: https://github.com/microsoft/testfx/issues/3371

Worth trying to rally behind it if we want more flexibility and options for the test explorer.

**Comment by rigtigeEmil** [comment]
Ah, that's a shame. I'll follow the issue and see if there is any traction on it. Thanks!
