### ISSUE TITLE
New Version (0.1.966) causes build errors: type errors due to Boxing Issues and INumbers?

### ISSUE THREAD

**Issue by HarryCordewener** [thomhurst/TUnit#797]
In updating from Version `0.1.877` to `0.1.966`, my TUnit tests have suddenly stopped being valid. 
I've added a PR that shows this change, and the errors attached:

https://github.com/SharpMUSH/SharpMUSH/pull/60 
https://github.com/SharpMUSH/SharpMUSH/actions/runs/11219273148/job/31184856701?pr=60

```
5>BooleanExpressionUnitTests.cs(43,51): Error CS0315 : The type 'bool' cannot be used as type parameter 'TActual' in the generic type or method 'NumberIsExtensions.IsEqualTo<TActual>(IValueSource<TActual>, TActual, string)'. There is no boxing conversion from 'bool' to 'System.Numerics.INumber<bool>'.
5>PatternUnitTests.cs(29,5): Error CS0315 : The type 'bool' cannot be used as type parameter 'TActual' in the generic type or method 'NumberIsExtensions.IsEqualTo<TActual>(IValueSource<TActual>, TActual, string)'. There is no boxing conversion from 'bool' to 'System.Numerics.INumber<bool>'.
5>NameList.cs(24,5): Error CS0315 : The type 'SharpMUSH.Library.Models.DBRef' cannot be used as type parameter 'TActual' in the generic type or method 'NumberIsExtensions.IsEqualTo<TActual>(IValueSource<TActual>, TActual, string)'. There is no boxing conversion from 'SharpMUSH.Library.Models.DBRef' to 'System.Numerics.INumber<SharpMUSH.Library.Models.DBRef>'.
5>BooleanExpressionUnitTests.cs(58,51): Error CS0315 : The type 'bool' cannot be used as type parameter 'TActual' in the generic type or method 'NumberIsExtensions.IsEqualTo<TActual>(IValueSource<TActual>, TActual, string)'. There is no boxing conversion from 'bool' to 'System.Numerics.INumber<bool>'.
5>BooleanExpressionUnitTests.cs(72,47): Error CS0315 : The type 'bool' cannot be used as type parameter 'TActual' in the generic type or method 'NumberIsExtensions.IsEqualTo<TActual>(IValueSource<TActual>, TActual, string)'. There is no boxing conversion from 'bool' to 'System.Numerics.INumber<bool>'.
5>NameList.cs(35,5): Error CS0315 : The type 'SharpMUSH.Library.Models.DBRef' cannot be used as type parameter 'TActual' in the generic type or method 'NumberIsExtensions.IsEqualTo<TActual>(IValueSource<TActual>, TActual, string)'. There is no boxing conversion from 'SharpMUSH.Library.Models.DBRef' to 'System.Numerics.INumber<SharpMUSH.Library.Models.DBRef>'.
5>AnsiStringUnitTests.cs(140,35): Error CS0311 : The type 'MarkupString.MarkupStringModule.MarkupString' cannot be used as type parameter 'TActual' in the generic type or method 'NumberIsExtensions.IsEqualTo<TActual>(IValueSource<TActual>, TActual, string)'. There is no implicit reference conversion from 'MarkupString.MarkupStringModule.MarkupString' to 'System.Numerics.INumber<MarkupString.MarkupStringModule.MarkupString>'.
5>------- Finished building project: SharpMUSH.Tests. Succeeded: False. Errors: 7. Warnings: 0
```

**Comment by thomhurst** [comment]
Apologies @HarryCordewener I did some major refactoring of the assertions library.

I'll have a fix out shortly!

**Comment by thomhurst** [comment]
@HarryCordewener can you try 0.1.971

**Comment by HarryCordewener** [comment]
@thomhurst - Some of the errors have gone away. Some have not.

```
6>NameList.cs(24,5): Error CS0315 : The type 'SharpMUSH.Library.Models.DBRef' cannot be used as type parameter 'TActual' in the generic type or method 'NumberIsExtensions.IsEqualTo<TActual>(IValueSource<TActual>, TActual, string)'. There is no boxing conversion from 'SharpMUSH.Library.Models.DBRef' to 'System.Numerics.INumber<SharpMUSH.Library.Models.DBRef>'.
6>NameList.cs(35,5): Error CS0315 : The type 'SharpMUSH.Library.Models.DBRef' cannot be used as type parameter 'TActual' in the generic type or method 'NumberIsExtensions.IsEqualTo<TActual>(IValueSource<TActual>, TActual, string)'. There is no boxing conversion from 'SharpMUSH.Library.Models.DBRef' to 'System.Numerics.INumber<SharpMUSH.Library.Models.DBRef>'.
6>AnsiStringUnitTests.cs(140,35): Error CS0311 : The type 'MarkupString.MarkupStringModule.MarkupString' cannot be used as type parameter 'TActual' in the generic type or method 'NumberIsExtensions.IsEqualTo<TActual>(IValueSource<TActual>, TActual, string)'. There is no implicit reference conversion from 'MarkupString.MarkupStringModule.MarkupString' to 'System.Numerics.INumber<MarkupString.MarkupStringModule.MarkupString>'.
```

DBRef is a struct: https://github.com/SharpMUSH/SharpMUSH/blob/7f69512023f30a025a295948a9cd63d877328944/SharpMUSH.Library/Models/DBref.cs#L9
MarkupString is an F# type (Aka, a class). 
https://github.com/SharpMUSH/SharpMUSH/blob/7f69512023f30a025a295948a9cd63d877328944/SharpMUSH.MarkupString/MarkupString.fs

Definitely not Numbers though.

**Comment by thomhurst** [comment]
@HarryCordewener basically there's conflicting generic method signatures so there's two options:

Use IsEquatableOrEqualTo

Or import the namespace TUnit.Assertions.Extensions.Generic to keep using the standard IsEqualTo.

Also you'll need to update to 0.1.980 for the new namespace as I've just added it.

**Comment by HarryCordewener** [comment]
These are rather typical signatures, so I suspect that's going to cause chaos in the future. 
I'll try out importing those namespaces.

**Comment by HarryCordewener** [comment]
Using IsEquatableOrEqualTo allowed the build.
Importing the namespace of course causes a bunch of Ambiguous references.

**Comment by thomhurst** [comment]
Yeah it's really annoying..I can't think of a way around it. I want the specific generic constraint versions because they allow more custom controls such as .Within(tolerance)

Might just be a pain point we have to live with.

**Comment by c-schembri** [comment]
I have noticed this issue crop up with assertions that check variables of various enums. Is this expected behaviour? I would have thought an enum is a 'kind of number'. Regardless, is `IsEquatableOrEqualTo` the correct assertion for checking the enums?

**Comment by thomhurst** [comment]
> I have noticed this issue crop up with assertions that check variables of various enums. Is this expected behaviour? I would have thought an enum is a 'kind of number'. Regardless, is `IsEquatableOrEqualTo` the correct assertion for checking the enums?

Yeah it'll call object.Equals, and as enums are just int/value types under the hood, that'll work fine
