### ISSUE TITLE
DataSourceGeneratorAttribute calls GenerateDataSources too often

### ISSUE THREAD

**Issue by dev-in-disguise** [thomhurst/TUnit#818]
An attribute that implements one of the `DataSourceGeneratorAttribute` variants can be applied to a test method multiple times. This should lead to one test case and one execution of the `GenerateDataSources` method per applied attribute.

The following example leads to three test cases and 9 executions of `GenerateDataSources` with the console output 44, 47 & 50:

```
public class Test
{
    [AutoData<int>]
    [AutoData<int>]
    [AutoData<int>]
    [Test]
    public async Task TestOne(int value)
    {
        Console.WriteLine(value);
    }
}

public class AutoDataAttribute<T> : DataSourceGeneratorAttribute<T>
{
    private static int i = 0;
    public override IEnumerable<T> GenerateDataSources(DataGeneratorMetadata dataGeneratorMetadata)
    {
        if (typeof(T) == typeof(int))
        {
            var array = new T [] { (T)(object)(42 + i) };
            i++;
            return array;
        }
        
        throw new NotImplementedException();
    }
}
```

**Comment by thomhurst** [comment]
@dev-in-disguise have you tried on v0.1.984?

**Comment by dev-in-disguise** [comment]
As usual you're faster in fixing and providing new features than I can come up with an issue 🤣 
With the newest version this issue no longer exists. Thanks @thomhurst !
