### ISSUE TITLE
Possible issue with dotnet vstest

### ISSUE THREAD

**Issue by LaszloLueck** [thomhurst/TUnit#827]
Hi,
I come from XUnit and on the console the tests work perfectly with `dotnet test`.
In the CI/CD process, I have a build stage in which the project and the test project are created in different directories (e.g. test_output and build_output).
I then always start the unit tests in the test stage with 

`dotnet vstest test_output/FancyProjectTests.dll --logger ‘trx;LogFileName=TestResults.trx’`

This does not work, the error message is:
```
Error:
  An assembly specified in the application dependencies manifest (testhost.deps.json) was not found:
    package: ‘Newtonsoft.Json’, version: ‘13.0.3’
    path: ‘lib/netstandard2.0/Newtonsoft.Json.dll’
. Please check the diagnostic logs for more information.
```

When I run the command on my PC, I get the same error. The same project compiled as XUnit works fine this way.
I have added the `Newtonsoft.Json 13.03` version to my test project via Nuget for testing, but without success, the error still occurs.

Regards
Laszlo

**Comment by LaszloLueck** [comment]
Short update,
even when i try `dotnet test test_output/FancyProjectTests.dll` from my CI-Test-Stage or from the console the error occurs.
Sorry, output partly in german...
```
dotnet vstest FancyProjectTests.dll
VSTest-Version 17.11.0 (arm64)

Die Testausführung wird gestartet, bitte warten...
Insgesamt 1 Testdateien stimmten mit dem angegebenen Muster überein.
Error:
  An assembly specified in the application dependencies manifest (testhost.deps.json) was not found:
    package: 'Newtonsoft.Json', version: '13.0.1'
    path: 'lib/netstandard2.0/Newtonsoft.Json.dll'
Der TestHost-Prozess für die Quelle(n) /Users/user/projekte/fancyproject/fancyprojecttest/bin/Release/net8.0/FancyProjectTest.dll wurde mit folgendem Fehler beendet: Error:
  An assembly specified in the application dependencies manifest (testhost.deps.json) was not found:
    package: 'Newtonsoft.Json', version: '13.0.1'
    path: 'lib/netstandard2.0/Newtonsoft.Json.dll'
. Weitere Informationen finden Sie in den Diagnoseprotokollen.

Testlauf abgebrochen.
```

I can start the command `dotnet test` with the option `-d <DiagFile.txt>`. Is it helpful for you if I provide you with the file?

**Comment by thomhurst** [comment]
Heya.

So VSTest was the old Microsoft test runner.

TUnit is built on top of the newer Microsoft.Testing.Platform. It doesn't even know about VSTest. 

This means your VSTest commands won't work.

You can use dotnet run, or dotnet test, or publish an executable, all of which will work. But not VSTest.

If you do `dotnet run --showmeoptions` you'll see various CLI flags you can use with TUnit. 

Hopefully you can achieve what you need.

**Comment by LaszloLueck** [comment]
Ui, quick reply, thank you.
Unfortunately, this does not work with `dotnet test` either.

**Comment by thomhurst** [comment]
What doesn't? Trx?

**Comment by thomhurst** [comment]
Flags are here : https://thomhurst.github.io/TUnit/docs/tutorial-extras/command-line-flags

**Comment by thomhurst** [comment]
And you need to install a separate trx package. Details here: https://thomhurst.github.io/TUnit/docs/extensions/

**Comment by thomhurst** [comment]
> Heya.
> 
> So VSTest was the old Microsoft test runner.
> 
> TUnit is built on top of the newer Microsoft.Testing.Platform. It doesn't even know about VSTest.
> 
> This means your VSTest commands won't work.
> 
> You can use dotnet run, or dotnet test, or publish an executable, all of which will work. But not VSTest.
> 
> If you do `dotnet run --showmeoptions` you'll see various CLI flags you can use with TUnit.
> 
> Hopefully you can achieve what you need.

Sorry just seen this. If you're using a dll you need to use `dotnet exec` instead of dotnet test I think.

Dotnet test is for project files

**Comment by LaszloLueck** [comment]
Yap,
with `dotnet exec` the tests locally work.
On my CI-Pipeline not, because there is not an option for an output like trx.
Also the option `--logger` or else is missing, thats why `dotnet exec` executes the dll as an app not a test.

**Comment by LaszloLueck** [comment]
I'm going to revise my build pipeline as a workaround, i don't want switch back to XUnit.
The build stage builds the main project and the test stage builds the test project (with the main project, as it is a reference in the test).
But then I can call `dotnet test` on the csproj with all the trx-stuff.

Regards

**Comment by thomhurst** [comment]
Install nuget package Microsoft.Testing.Extensions.TrxReport and then try

dotnet run YourProject.csproj --report-trx --report-trx-filename SomeFilename.trx

**Comment by LaszloLueck** [comment]
And finally, the pipeline is green!
I have adapted the command as follows, now the test stage works without any problems
`dotnet run --project MyFancyTestProject/MyFancyTestProject.csproj --report-trx --report-trx-filename TestResults.trx --results-directory TestResults`
Thank you for your help.

**Comment by thomhurst** [comment]
Glad to help 😄
