### ISSUE TITLE
Do we really need the expression in the assertion message?

### ISSUE THREAD

**Issue by vbreuss** [thomhurst/TUnit#855]
Currently the assertion message contains the expression which is quite cleverly built up through the assertion chain. However it is not always correct, e.g.
```
await Assert.That(action).ThrowsException();
```
results in an expression
```
Assert.That(action).ThrowsException.OfAnyType()
```

For me, I don't think it adds much value, I would be more interested in the file and line number of the error.

What are your thoughts on it, @thomhurst?

**Comment by thomhurst** [comment]
I think the real benefit is when you have an assertion scope. 

Imagine you had 10 assertions.

Showing the expression allows you to see exactly which one failed.

**Comment by vbreuss** [comment]
Do you think it is realistic to really get the correct Expression in all cases?

If I am interested in which case failed, I could distinguish them via Because.

**Comment by thomhurst** [comment]
> Do you think it is realistic to really get the correct Expression in all cases?
> 
> If I am interested in which case failed, I could distinguish them via Because.

If assertions aren't within a scope, then maybe it's not necessary. 

But I think I'd still like it in scoped scenarios because it makes things quicker to diagnose than trying to decipher / find which message relates to which assertion.

What do you think?

We could have logic to not show it if the assertion scope is null, which should be quite easy actually.

Most people probably won't use scopes, so it'd omit it in most scenarios

**Comment by vbreuss** [comment]
> But I think I'd still like it in scoped scenarios because it makes things quicker to diagnose than trying to decipher / find which message relates to which assertion.
> 
> What do you think?
> 
> We could have logic to not show it if the assertion scope is null, which should be quite easy actually.
> 
> Most people probably won't use scopes, so it'd omit it in most scenarios

I think, that if we include the expression, we should append them everywhere. Having more diagnostic information at the end of the assertion message can't hurt.
However, we then should make sure, that the expression really matches the assertion, as it could otherwise be confusing...
