### ISSUE TITLE
Dynamic Skip

### ISSUE THREAD

**Issue by vbreuss** [thomhurst/TUnit#888]
I think it would be a great idea to incorporate dynamic skip, similar to https://github.com/xunit/xunit/issues/2073, by adding the following methods:
```
Assert.Skip(string reason);
Assert.SkipIf(bool condition, string reason);
```
which will both throw a `SkipTestException`.

The challenge will be to keep `TUnit.Engine` and `TUnit.Assertions` separate, but maybe checking for a "SkipTestException" with a fixed namespace in the Engine project?

**Comment by thomhurst** [comment]
TUnit already works off of a skipped exception so this will be easy to do 😄

**Comment by thomhurst** [comment]
Although actually now you say it, the separate projects and namespace could be challenging.

The question also arises what if the assertion library is used in another project... It wouldn't work and also wouldn't make sense.

It'd work if we could make an extension method in the core library, but C# doesn't currently support static type extensions.

Also, I'd opt for just the basic skip method I think. The if can be natively wrapped around the call.

**Comment by vbreuss** [comment]
> The question also arises what if the assertion library is used in another project... It wouldn't work and also wouldn't make sense.

I think, that for this case adding/using another skip method is a legitimate option.
Note, that xunit decided to treat all exceptions where the message starts with `$XunitDynamicSkip$` as an exception resulting in a skipped reason.

Maybe such an approach would also be feasible?

> Also, I'd opt for just the basic skip method I think. The if can be natively wrapped around the call.

As it is a static method on a static class, it cannot be directly wrapped, but could of course be implemented differently.

That's why [xunit will implement it as follows](https://xunit.net/docs/getting-started/v3/whats-new):
> Three new assertions have been added to support dynamically skipping a test at runtime.
> `Assert.Skip(string message)`
> `Assert.SkipUnless(bool condition, string reason)` will dynamically skip the test only if condition is false
> `Assert.SkipWhen(bool condition, string reason)` will dynamically skip the test only if condition is true

However, after thinking about it, I think it would be better to move this to a separate static class (and not integrate it into the `Assert` class)
```csharp
public static class Skip
{
    public void Test(string reason); // skips the test unconditionally
    public void When(bool condition, string reason);
    public void Unless(bool condition, string reason);
}
```
This way, you could omit the `When` and `Unless` case and a user could use a custom static class instead.
