### ISSUE TITLE
Directory structure in TUnit.Assertions

### ISSUE THREAD

**Issue by vbreuss** [thomhurst/TUnit#890]
I find myself often jumping between the assertion conditions and the corresponding extensions and they are quite far apart in the project. As they belong together, I think it would be great, if the sources are also near each other, e.g. similar to the following structure:
![image](https://github.com/user-attachments/assets/a7aa03bd-5d8f-4277-9230-bd197c94f41c)
instead of
![image](https://github.com/user-attachments/assets/d2ba8dcc-a166-48f2-95df-0df27ed61eb6)

What are your thoughts, @thomhurst?

**Comment by thomhurst** [comment]
Yup fine by me
