### ISSUE TITLE
Unclear precedence of AND and OR

### ISSUE THREAD

**Issue by vbreuss** [thomhurst/TUnit#891]
I couldn't find anything in the [documentation](https://thomhurst.github.io/TUnit/docs/category/tutorial---assertions) with regards to the precedence between [AND](https://thomhurst.github.io/TUnit/docs/tutorial-assertions/and-conditions) and [OR](https://thomhurst.github.io/TUnit/docs/tutorial-assertions/or-conditions).

Consider the following test:
```csharp
[Test]
public async Task And_Or_Precedence_Test()
{
    char[] sut = "CD".ToCharArray();

    await Assert.That(sut)
        .Contains('A').And
        .Contains('B').Or
        .Contains('C').And
        .Contains('D');
}
```

I would have expected the test to fail, as I would expect the condition to be interpreted as `(A && B) || (C && D)`, to be in line with the [operator precedence](https://thomhurst.github.io/TUnit/docs/category/tutorial---assertions) in C#.

However, this test succeeds, because `A && B || C && D` seems to be interpreted as `(((A && B) || C) && D)`.

**Comment by thomhurst** [comment]
Did the analyzer kick in?

**Comment by vbreuss** [comment]
No, I didn't see any analyzer...

**Comment by thomhurst** [comment]
Hmm I'll need to check then.

There should be an analyzer flagging mixing of and+or..for the reason you mentioned, it can be confusing how the logic will evaluate.

So the analyzer allows chained ANDs or chained ORs, but should flag if a mix is used.

**Comment by thomhurst** [comment]
Analyzer showing for me fine: 
![image](https://github.com/user-attachments/assets/ecdebfe9-1e0b-4383-9d59-e5b8ee44f821)

**Comment by vbreuss** [comment]
Hmm, after restarting Visual Studio, I could see the analyzer:
![image](https://github.com/user-attachments/assets/4b472573-f0ed-442e-9f3a-64fcbe856783)
*It was probably an issue with the preview version.*

However, as this is only an indication (that could be turned off), wouldn't it make sense to make an explicit choice of precedence in these cases?
Or state, that this is not supported and throw an exception when both are mixed, so as not to lead to false positives in tests?

**Comment by thomhurst** [comment]
Probably throwing would be better, as:

```csharp
await Assert.That(sut)
        .Contains('A')
        .And.Contains('B')
        .Or
        .Contains('C');
```

```csharp
await Assert.That(sut)
        .Contains('A')
        .And
        .Contains('B')
        .Or.Contains('C');
```

Both are the exact same code, but due to the formatting/placement of it you might think it means something different to what it does.
