### ISSUE TITLE
[.NET 9] IsEqualTo is ambiguous for numbers when using TUnit.Assertions.Extensions.Generic

### ISSUE THREAD

**Issue by BarionLP** [thomhurst/TUnit#922]
The call [IsEqualTo] is ambiguous between the following methods or properties: 'TUnit.Assertions.Extensions.NumberIsExtensions.IsEqualTo<TActual>(TUnit.Assertions.AssertConditions.Interfaces.IValueSource<TActual>, TActual, string)' and 'TUnit.Assertions.Extensions.Generic.GenericIsExtensions.IsEqualTo<TActual>(TUnit.Assertions.AssertConditions.Interfaces.IValueSource<TActual>, TActual, string)'

I have multiple cases where it would be nice to have both methods in the same test class (of course I could always split the class but that creates a bunch of small files)

I assume you implement IsEqualTo for each number type (in my case int) and for IEquatable<T> but all number types implement IEquatable<T>. ~~In .NET 9 you can fix this by adding the OverloadResolutionPriorityAttribute to one of the methods. but i think you only need one of the methods.~~ OverloadResolutionPriorityAttribute only seems works for methods in the same class.

**Comment by thomhurst** [comment]
Yeah this is really bugging me. I've created IsEqualOrEquatable to as a workaround for now, but would really like to sort it. Unfortunately restricted by the language

**Comment by BarionLP** [comment]
I opened a discussion on the dotnet repo about the `OverloadResolutionPriorityAttribute` because I think it should affect overloading in general https://github.com/dotnet/runtime/discussions/108963

**Comment by BarionLP** [comment]
they specifically rejected this feature https://github.com/dotnet/csharplang/blob/main/meetings%2F2024%2FLDM-2024-05-13.md

maybe there is another option to solve this issue? e.g. with type matching?

**Comment by julealgon** [comment]
@BarionLP would you mind creating a small repro of this issue? I can try taking a look and see if I can come up with something.

I had never heard of TUnit until today so this is an opportunity to check the library as well.

**Comment by BarionLP** [comment]
> would you mind creating a small repro of this issue

@julealgon https://github.com/BarionLP/TUnitAmbigousMethodCall

**Comment by thomhurst** [comment]
I believe I've fixed this in v0.1.1066 !
I constrained the 'generic' `IsEqualTo` to reference types. And the basic value types (numbers, bools, etc.) Should have their own specific extensions still. Let me know if this solves your problem.

**Comment by BarionLP** [comment]
@thomhurst it fixes this problem but now i can't compare custom structs...

**Comment by thomhurst** [comment]
> @thomhurst it fixes this problem but now i can't compare custom structs...

Can you use IsEquatableOrEqualTo for structs? I know it's not ideal but reference classes will account for most scenarios I think. So this other method will cater for the structs.

**Comment by thomhurst** [comment]
I might actually rename it to `IsEqualStructTo` so it's clearer to the end user.

**Comment by BarionLP** [comment]
> I might actually rename it to `IsEqualStructTo` so it's clearer to the end user.

i would prefer `IsStructEqualTo` or `IsEqualToStruct`.
 anyway that should do it. even though not being ideal. maybe you can find a way to combine some of these methods (i don't know enough to know why they are separate in the first place)

**Comment by thomhurst** [comment]
Right I think I've finally fixed this in v0.1.1082
