### ISSUE TITLE
`[Arguments]` value not being transferred properly

### ISSUE THREAD

**Issue by viceroypenguin** [thomhurst/TUnit#925]
The following code does not compile properly when used with `TUnit`.

```cs
public const int DummyValue = 123;
[Test]
[Arguments(DummyValue)]
public void Test(int dummy)
{
}
```

The problem is that the text `DummyValue` is used in the generated code directly, rather than the underlying value. Since `DummyValue` is not qualified and refers to a local constant, it is not properly referenced by the generated code. 

### Resolution:
Use something similar to the following code:
```cs
private static string? GetTypedConstantString(this TypedConstant tc) =>
	tc.Kind switch
	{
		TypedConstantKind.Array => $"[{string.Join(", ", tc.Values.Select(GetTypedConstantString))}]",
		_ => tc.ToCSharpString(),
	};
```

**Comment by thomhurst** [comment]
Thanks for the sponsor @viceroypenguin ! ❤️ 

And thanks for the report. I think I've fixed it. Just pushing a PR through now.

**Comment by viceroypenguin** [comment]
Thank you for such a quick fix! Already tested and working.
