### ISSUE TITLE
Assert.Fail should still be included in Assert class

### ISSUE THREAD

**Issue by hquinn** [thomhurst/TUnit#965]
From a usability point of view, I believe having a single point of entry (i.e. `Assert`) which outlines all the different assertion behaviours is a good thing (analogous to FluentAssertions `Should()`). Having a consistent API like this allows users to not have to consult documentation for how to do simple tasks if it can be avoided. Although the new `Fail` class does provide additional functionality, I don't see why `Assert.Fail` was removed, when it could have simply returned `Fail.Test` instead.

**Comment by thomhurst** [comment]
Yep completely valid - The Assert API is much more accessible and more well-known about. I'll re-add it.

**Comment by vbreuss** [comment]
I want to add a different opinion on this:
For me **the most distinguishing feature** of the `TUnit` assertions library from other assertions libraries is the "async everything" approach. Now you have mixed sync and async methods on the `Assert` class which will cause confusion for users.

So if you insist on having the `Assert.Fail` method, I would at least make it `async` so it follows the same pattern...

**Comment by hquinn** [comment]
> I want to add a different opinion on this: For me **the most distinguishing feature** of the `TUnit` assertions library from other assertions libraries is the "async everything" approach. Now you have mixed sync and async methods on the `Assert` class which will cause confusion for users.
> 
> So if you insist on having the `Assert.Fail` method, I would at least make it `async` so it follows the same pattern...

From my understanding, the async/await model is to help chain assertions for certain scenarios. I don't know if chaining a `Assert.Fail` is useful or not, nor do I think it's confusing to users when analyzers are there to provide feedback back to developers. Having said that, if it is too confusing, then this change will also need to be applied to the `Fail` class (and possibly `Skip` if consistency is wanted).
