### ISSUE TITLE
MethodDataSource Matching Arguments Analyzer

### ISSUE THREAD

**Issue by thomhurst** [thomhurst/TUnit#969]

**Comment by viceroypenguin** [comment]
I assume this issue is here because `TUnit0010` is being triggered (now invalidly) for methods that have parameters?

**Comment by thomhurst** [comment]
Yep I will fix it at some point don't worry 😅 Might just have to suppress it in the mean time

**Comment by viceroypenguin** [comment]
No worries! Thanks! Just wanted to make sure I didn't open another issue for it. :)
