### ISSUE TITLE
[BUG]: Sematic Classification is currently unavailable

### ISSUE THREAD

**Issue by viceroypenguin** [thomhurst/TUnit#970]
I'm currently getting an exception in VS 17.12 preview 3 when using TUnit v0.1.1090. Here's the stack trace. 

![image](https://github.com/user-attachments/assets/04320e18-6f20-4031-b2c6-b510cbd972bd)

**Comment by thomhurst** [comment]
Can you post the stscktrace as text so I can see line numbers etc?

**Comment by viceroypenguin** [comment]
Looks like it may have been a VS-drunk situation. Re-upgraded to v0.1.1090, and it's fine now. Thanks though!
